// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: proto/analysis/specialist.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Data sent by the Master binary (Chat-Lab)
type AnalysisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`                                                // Unique identifier for BadgerDB correlation
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                                                                     // Raw text to be processed by the model
	Tags          map[string]string      `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Metadata for contextual filtering (e.g., room_id)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisRequest) Reset() {
	*x = AnalysisRequest{}
	mi := &file_proto_analysis_specialist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisRequest) ProtoMessage() {}

func (x *AnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analysis_specialist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisRequest.ProtoReflect.Descriptor instead.
func (*AnalysisRequest) Descriptor() ([]byte, []int) {
	return file_proto_analysis_specialist_proto_rawDescGZIP(), []int{0}
}

func (x *AnalysisRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *AnalysisRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AnalysisRequest) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// Response from the Specialist binary (m2cgen transpiled code)
type AnalysisResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Score        float32                `protobuf:"fixed32,1,opt,name=score,proto3" json:"score,omitempty"`                                 // Probability score between 0.0 and 1.0
	Label        string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`                                   // Human-readable verdict (e.g., "SPAM", "TOXIC")
	ModelVersion string                 `protobuf:"bytes,3,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"` // Identifier for the specific model version used
	// Performance metrics for Lead Time monitoring
	ProcessTimeMs int64 `protobuf:"varint,4,opt,name=process_time_ms,json=processTimeMs,proto3" json:"process_time_ms,omitempty"` // Internal execution time in milliseconds
	// Health and status tracking
	Status        string `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // Status message (e.g., "OK", "ERROR_INFERENCE")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisResponse) Reset() {
	*x = AnalysisResponse{}
	mi := &file_proto_analysis_specialist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisResponse) ProtoMessage() {}

func (x *AnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analysis_specialist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisResponse.ProtoReflect.Descriptor instead.
func (*AnalysisResponse) Descriptor() ([]byte, []int) {
	return file_proto_analysis_specialist_proto_rawDescGZIP(), []int{1}
}

func (x *AnalysisResponse) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *AnalysisResponse) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *AnalysisResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *AnalysisResponse) GetProcessTimeMs() int64 {
	if x != nil {
		return x.ProcessTimeMs
	}
	return 0
}

func (x *AnalysisResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_analysis_specialist_proto protoreflect.FileDescriptor

const file_proto_analysis_specialist_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/analysis/specialist.proto\x12\n" +
	"specialist\"\xbe\x01\n" +
	"\x0fAnalysisRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x129\n" +
	"\x04tags\x18\x03 \x03(\v2%.specialist.AnalysisRequest.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa3\x01\n" +
	"\x10AnalysisResponse\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x02R\x05score\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12#\n" +
	"\rmodel_version\x18\x03 \x01(\tR\fmodelVersion\x12&\n" +
	"\x0fprocess_time_ms\x18\x04 \x01(\x03R\rprocessTimeMs\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status2Y\n" +
	"\x11SpecialistService\x12D\n" +
	"\aAnalyze\x12\x1b.specialist.AnalysisRequest\x1a\x1c.specialist.AnalysisResponseB\x19Z\x17analysis/proto/pb-go;pbb\x06proto3"

var (
	file_proto_analysis_specialist_proto_rawDescOnce sync.Once
	file_proto_analysis_specialist_proto_rawDescData []byte
)

func file_proto_analysis_specialist_proto_rawDescGZIP() []byte {
	file_proto_analysis_specialist_proto_rawDescOnce.Do(func() {
		file_proto_analysis_specialist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_analysis_specialist_proto_rawDesc), len(file_proto_analysis_specialist_proto_rawDesc)))
	})
	return file_proto_analysis_specialist_proto_rawDescData
}

var file_proto_analysis_specialist_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_analysis_specialist_proto_goTypes = []any{
	(*AnalysisRequest)(nil),  // 0: specialist.AnalysisRequest
	(*AnalysisResponse)(nil), // 1: specialist.AnalysisResponse
	nil,                      // 2: specialist.AnalysisRequest.TagsEntry
}
var file_proto_analysis_specialist_proto_depIdxs = []int32{
	2, // 0: specialist.AnalysisRequest.tags:type_name -> specialist.AnalysisRequest.TagsEntry
	0, // 1: specialist.SpecialistService.Analyze:input_type -> specialist.AnalysisRequest
	1, // 2: specialist.SpecialistService.Analyze:output_type -> specialist.AnalysisResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_analysis_specialist_proto_init() }
func file_proto_analysis_specialist_proto_init() {
	if File_proto_analysis_specialist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_analysis_specialist_proto_rawDesc), len(file_proto_analysis_specialist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_analysis_specialist_proto_goTypes,
		DependencyIndexes: file_proto_analysis_specialist_proto_depIdxs,
		MessageInfos:      file_proto_analysis_specialist_proto_msgTypes,
	}.Build()
	File_proto_analysis_specialist_proto = out.File
	file_proto_analysis_specialist_proto_goTypes = nil
	file_proto_analysis_specialist_proto_depIdxs = nil
}
