// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: proto/chat/chat.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PresenceEvent_Type int32

const (
	PresenceEvent_JOINED PresenceEvent_Type = 0
	PresenceEvent_LEFT   PresenceEvent_Type = 1
)

// Enum value maps for PresenceEvent_Type.
var (
	PresenceEvent_Type_name = map[int32]string{
		0: "JOINED",
		1: "LEFT",
	}
	PresenceEvent_Type_value = map[string]int32{
		"JOINED": 0,
		"LEFT":   1,
	}
)

func (x PresenceEvent_Type) Enum() *PresenceEvent_Type {
	p := new(PresenceEvent_Type)
	*p = x
	return p
}

func (x PresenceEvent_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PresenceEvent_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_chat_chat_proto_enumTypes[0].Descriptor()
}

func (PresenceEvent_Type) Type() protoreflect.EnumType {
	return &file_proto_chat_chat_proto_enumTypes[0]
}

func (x PresenceEvent_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PresenceEvent_Type.Descriptor instead.
func (PresenceEvent_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{8, 0}
}

type GetMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          int64                  `protobuf:"varint,1,opt,name=room,proto3" json:"room,omitempty"`
	Cursor        *string                `protobuf:"bytes,2,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageRequest) Reset() {
	*x = GetMessageRequest{}
	mi := &file_proto_chat_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageRequest) ProtoMessage() {}

func (x *GetMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageRequest.ProtoReflect.Descriptor instead.
func (*GetMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{0}
}

func (x *GetMessageRequest) GetRoom() int64 {
	if x != nil {
		return x.Room
	}
	return 0
}

func (x *GetMessageRequest) GetCursor() string {
	if x != nil && x.Cursor != nil {
		return *x.Cursor
	}
	return ""
}

type GetMessageResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MessageResponse []*MessageResponse     `protobuf:"bytes,1,rep,name=message_response,json=messageResponse,proto3" json:"message_response,omitempty"`
	Cursor          *string                `protobuf:"bytes,2,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetMessageResponse) Reset() {
	*x = GetMessageResponse{}
	mi := &file_proto_chat_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageResponse) ProtoMessage() {}

func (x *GetMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageResponse.ProtoReflect.Descriptor instead.
func (*GetMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{1}
}

func (x *GetMessageResponse) GetMessageResponse() []*MessageResponse {
	if x != nil {
		return x.MessageResponse
	}
	return nil
}

func (x *GetMessageResponse) GetCursor() string {
	if x != nil && x.Cursor != nil {
		return *x.Cursor
	}
	return ""
}

type MessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageResponse) Reset() {
	*x = MessageResponse{}
	mi := &file_proto_chat_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResponse) ProtoMessage() {}

func (x *MessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResponse.ProtoReflect.Descriptor instead.
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{2}
}

func (x *MessageResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageResponse) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *MessageResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type PostMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostMessageRequest) Reset() {
	*x = PostMessageRequest{}
	mi := &file_proto_chat_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMessageRequest) ProtoMessage() {}

func (x *PostMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMessageRequest.ProtoReflect.Descriptor instead.
func (*PostMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{3}
}

func (x *PostMessageRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *PostMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type PostMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostMessageResponse) Reset() {
	*x = PostMessageResponse{}
	mi := &file_proto_chat_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMessageResponse) ProtoMessage() {}

func (x *PostMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMessageResponse.ProtoReflect.Descriptor instead.
func (*PostMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{4}
}

func (x *PostMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_proto_chat_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{5}
}

func (x *ConnectRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type ChatEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ChatEvent_Message
	//	*ChatEvent_Presence
	Event         isChatEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatEvent) Reset() {
	*x = ChatEvent{}
	mi := &file_proto_chat_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatEvent) ProtoMessage() {}

func (x *ChatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatEvent.ProtoReflect.Descriptor instead.
func (*ChatEvent) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{6}
}

func (x *ChatEvent) GetEvent() isChatEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ChatEvent) GetMessage() *MessageEvent {
	if x != nil {
		if x, ok := x.Event.(*ChatEvent_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *ChatEvent) GetPresence() *PresenceEvent {
	if x != nil {
		if x, ok := x.Event.(*ChatEvent_Presence); ok {
			return x.Presence
		}
	}
	return nil
}

type isChatEvent_Event interface {
	isChatEvent_Event()
}

type ChatEvent_Message struct {
	Message *MessageEvent `protobuf:"bytes,1,opt,name=message,proto3,oneof"`
}

type ChatEvent_Presence struct {
	Presence *PresenceEvent `protobuf:"bytes,2,opt,name=presence,proto3,oneof"`
}

func (*ChatEvent_Message) isChatEvent_Event() {}

func (*ChatEvent_Presence) isChatEvent_Event() {}

type MessageEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageEvent) Reset() {
	*x = MessageEvent{}
	mi := &file_proto_chat_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEvent) ProtoMessage() {}

func (x *MessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEvent.ProtoReflect.Descriptor instead.
func (*MessageEvent) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{7}
}

func (x *MessageEvent) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageEvent) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *MessageEvent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type PresenceEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          PresenceEvent_Type     `protobuf:"varint,2,opt,name=type,proto3,enum=chat.v1.PresenceEvent_Type" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresenceEvent) Reset() {
	*x = PresenceEvent{}
	mi := &file_proto_chat_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceEvent) ProtoMessage() {}

func (x *PresenceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceEvent.ProtoReflect.Descriptor instead.
func (*PresenceEvent) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{8}
}

func (x *PresenceEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PresenceEvent) GetType() PresenceEvent_Type {
	if x != nil {
		return x.Type
	}
	return PresenceEvent_JOINED
}

var File_proto_chat_chat_proto protoreflect.FileDescriptor

const file_proto_chat_chat_proto_rawDesc = "" +
	"\n" +
	"\x15proto/chat/chat.proto\x12\achat.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"O\n" +
	"\x11GetMessageRequest\x12\x12\n" +
	"\x04room\x18\x01 \x01(\x03R\x04room\x12\x1b\n" +
	"\x06cursor\x18\x02 \x01(\tH\x00R\x06cursor\x88\x01\x01B\t\n" +
	"\a_cursor\"\x81\x01\n" +
	"\x12GetMessageResponse\x12C\n" +
	"\x10message_response\x18\x01 \x03(\v2\x18.chat.v1.MessageResponseR\x0fmessageResponse\x12\x1b\n" +
	"\x06cursor\x18\x02 \x01(\tH\x00R\x06cursor\x88\x01\x01B\t\n" +
	"\a_cursor\"\x9d\x01\n" +
	"\x0fMessageResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"G\n" +
	"\x12PostMessageRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"/\n" +
	"\x13PostMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\")\n" +
	"\x0eConnectRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\"}\n" +
	"\tChatEvent\x121\n" +
	"\amessage\x18\x01 \x01(\v2\x15.chat.v1.MessageEventH\x00R\amessage\x124\n" +
	"\bpresence\x18\x02 \x01(\v2\x16.chat.v1.PresenceEventH\x00R\bpresenceB\a\n" +
	"\x05event\"\x9a\x01\n" +
	"\fMessageEvent\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"w\n" +
	"\rPresenceEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12/\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1b.chat.v1.PresenceEvent.TypeR\x04type\"\x1c\n" +
	"\x04Type\x12\n" +
	"\n" +
	"\x06JOINED\x10\x00\x12\b\n" +
	"\x04LEFT\x10\x012\xd8\x01\n" +
	"\vChatService\x12E\n" +
	"\n" +
	"GetMessage\x12\x1a.chat.v1.GetMessageRequest\x1a\x1b.chat.v1.GetMessageResponse\x12H\n" +
	"\vPostMessage\x12\x1b.chat.v1.PostMessageRequest\x1a\x1c.chat.v1.PostMessageResponse\x128\n" +
	"\aConnect\x12\x17.chat.v1.ConnectRequest\x1a\x12.chat.v1.ChatEvent0\x01B\x18Z\x16chat-lab/proto/chat/v1b\x06proto3"

var (
	file_proto_chat_chat_proto_rawDescOnce sync.Once
	file_proto_chat_chat_proto_rawDescData []byte
)

func file_proto_chat_chat_proto_rawDescGZIP() []byte {
	file_proto_chat_chat_proto_rawDescOnce.Do(func() {
		file_proto_chat_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_chat_chat_proto_rawDesc), len(file_proto_chat_chat_proto_rawDesc)))
	})
	return file_proto_chat_chat_proto_rawDescData
}

var file_proto_chat_chat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_chat_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_chat_chat_proto_goTypes = []any{
	(PresenceEvent_Type)(0),       // 0: chat.v1.PresenceEvent.Type
	(*GetMessageRequest)(nil),     // 1: chat.v1.GetMessageRequest
	(*GetMessageResponse)(nil),    // 2: chat.v1.GetMessageResponse
	(*MessageResponse)(nil),       // 3: chat.v1.MessageResponse
	(*PostMessageRequest)(nil),    // 4: chat.v1.PostMessageRequest
	(*PostMessageResponse)(nil),   // 5: chat.v1.PostMessageResponse
	(*ConnectRequest)(nil),        // 6: chat.v1.ConnectRequest
	(*ChatEvent)(nil),             // 7: chat.v1.ChatEvent
	(*MessageEvent)(nil),          // 8: chat.v1.MessageEvent
	(*PresenceEvent)(nil),         // 9: chat.v1.PresenceEvent
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_proto_chat_chat_proto_depIdxs = []int32{
	3,  // 0: chat.v1.GetMessageResponse.message_response:type_name -> chat.v1.MessageResponse
	10, // 1: chat.v1.MessageResponse.created_at:type_name -> google.protobuf.Timestamp
	8,  // 2: chat.v1.ChatEvent.message:type_name -> chat.v1.MessageEvent
	9,  // 3: chat.v1.ChatEvent.presence:type_name -> chat.v1.PresenceEvent
	10, // 4: chat.v1.MessageEvent.created_at:type_name -> google.protobuf.Timestamp
	0,  // 5: chat.v1.PresenceEvent.type:type_name -> chat.v1.PresenceEvent.Type
	1,  // 6: chat.v1.ChatService.GetMessage:input_type -> chat.v1.GetMessageRequest
	4,  // 7: chat.v1.ChatService.PostMessage:input_type -> chat.v1.PostMessageRequest
	6,  // 8: chat.v1.ChatService.Connect:input_type -> chat.v1.ConnectRequest
	2,  // 9: chat.v1.ChatService.GetMessage:output_type -> chat.v1.GetMessageResponse
	5,  // 10: chat.v1.ChatService.PostMessage:output_type -> chat.v1.PostMessageResponse
	7,  // 11: chat.v1.ChatService.Connect:output_type -> chat.v1.ChatEvent
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_chat_chat_proto_init() }
func file_proto_chat_chat_proto_init() {
	if File_proto_chat_chat_proto != nil {
		return
	}
	file_proto_chat_chat_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_chat_chat_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_chat_chat_proto_msgTypes[6].OneofWrappers = []any{
		(*ChatEvent_Message)(nil),
		(*ChatEvent_Presence)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_chat_chat_proto_rawDesc), len(file_proto_chat_chat_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_chat_chat_proto_goTypes,
		DependencyIndexes: file_proto_chat_chat_proto_depIdxs,
		EnumInfos:         file_proto_chat_chat_proto_enumTypes,
		MessageInfos:      file_proto_chat_chat_proto_msgTypes,
	}.Build()
	File_proto_chat_chat_proto = out.File
	file_proto_chat_chat_proto_goTypes = nil
	file_proto_chat_chat_proto_depIdxs = nil
}
