# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto.chat import chat_service_pb2 as proto_dot_chat_dot_chat__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/chat/chat_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChatServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMessage = channel.unary_unary(
                '/chat.ChatService/GetMessage',
                request_serializer=proto_dot_chat_dot_chat__service__pb2.GetMessageRequest.SerializeToString,
                response_deserializer=proto_dot_chat_dot_chat__service__pb2.GetMessageResponse.FromString,
                _registered_method=True)
        self.PostMessage = channel.unary_unary(
                '/chat.ChatService/PostMessage',
                request_serializer=proto_dot_chat_dot_chat__service__pb2.PostMessageRequest.SerializeToString,
                response_deserializer=proto_dot_chat_dot_chat__service__pb2.PostMessageResponse.FromString,
                _registered_method=True)
        self.Connect = channel.unary_stream(
                '/chat.ChatService/Connect',
                request_serializer=proto_dot_chat_dot_chat__service__pb2.ConnectRequest.SerializeToString,
                response_deserializer=proto_dot_chat_dot_chat__service__pb2.ChatEvent.FromString,
                _registered_method=True)


class ChatServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PostMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Connect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMessage,
                    request_deserializer=proto_dot_chat_dot_chat__service__pb2.GetMessageRequest.FromString,
                    response_serializer=proto_dot_chat_dot_chat__service__pb2.GetMessageResponse.SerializeToString,
            ),
            'PostMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.PostMessage,
                    request_deserializer=proto_dot_chat_dot_chat__service__pb2.PostMessageRequest.FromString,
                    response_serializer=proto_dot_chat_dot_chat__service__pb2.PostMessageResponse.SerializeToString,
            ),
            'Connect': grpc.unary_stream_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=proto_dot_chat_dot_chat__service__pb2.ConnectRequest.FromString,
                    response_serializer=proto_dot_chat_dot_chat__service__pb2.ChatEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chat.ChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chat.ChatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.ChatService/GetMessage',
            proto_dot_chat_dot_chat__service__pb2.GetMessageRequest.SerializeToString,
            proto_dot_chat_dot_chat__service__pb2.GetMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PostMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.ChatService/PostMessage',
            proto_dot_chat_dot_chat__service__pb2.PostMessageRequest.SerializeToString,
            proto_dot_chat_dot_chat__service__pb2.PostMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/chat.ChatService/Connect',
            proto_dot_chat_dot_chat__service__pb2.ConnectRequest.SerializeToString,
            proto_dot_chat_dot_chat__service__pb2.ChatEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
