# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/chat/chat_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/chat/chat_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dproto/chat/chat_service.proto\x12\x04\x63hat\x1a\x1fgoogle/protobuf/timestamp.proto\"A\n\x11GetMessageRequest\x12\x0c\n\x04room\x18\x01 \x01(\x03\x12\x13\n\x06\x63ursor\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\t\n\x07_cursor\"e\n\x12GetMessageResponse\x12/\n\x10message_response\x18\x01 \x03(\x0b\x32\x15.chat.MessageResponse\x12\x13\n\x06\x63ursor\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\t\n\x07_cursor\"v\n\x0fMessageResponse\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12.\n\ncreated_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"6\n\x12PostMessageRequest\x12\x0f\n\x07room_id\x18\x01 \x01(\x03\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"&\n\x13PostMessageResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"!\n\x0e\x43onnectRequest\x12\x0f\n\x07room_id\x18\x01 \x01(\x03\"d\n\tChatEvent\x12%\n\x07message\x18\x01 \x01(\x0b\x32\x12.chat.MessageEventH\x00\x12\'\n\x08presence\x18\x02 \x01(\x0b\x32\x13.chat.PresenceEventH\x00\x42\x07\n\x05\x65vent\"s\n\x0cMessageEvent\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12.\n\ncreated_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"f\n\rPresenceEvent\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12&\n\x04type\x18\x02 \x01(\x0e\x32\x18.chat.PresenceEvent.Type\"\x1c\n\x04Type\x12\n\n\x06JOINED\x10\x00\x12\x08\n\x04LEFT\x10\x01\x32\xc6\x01\n\x0b\x43hatService\x12?\n\nGetMessage\x12\x17.chat.GetMessageRequest\x1a\x18.chat.GetMessageResponse\x12\x42\n\x0bPostMessage\x12\x18.chat.PostMessageRequest\x1a\x19.chat.PostMessageResponse\x12\x32\n\x07\x43onnect\x12\x14.chat.ConnectRequest\x1a\x0f.chat.ChatEvent0\x01\x42\x06Z\x04./pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.chat.chat_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004./pb'
  _globals['_GETMESSAGEREQUEST']._serialized_start=72
  _globals['_GETMESSAGEREQUEST']._serialized_end=137
  _globals['_GETMESSAGERESPONSE']._serialized_start=139
  _globals['_GETMESSAGERESPONSE']._serialized_end=240
  _globals['_MESSAGERESPONSE']._serialized_start=242
  _globals['_MESSAGERESPONSE']._serialized_end=360
  _globals['_POSTMESSAGEREQUEST']._serialized_start=362
  _globals['_POSTMESSAGEREQUEST']._serialized_end=416
  _globals['_POSTMESSAGERESPONSE']._serialized_start=418
  _globals['_POSTMESSAGERESPONSE']._serialized_end=456
  _globals['_CONNECTREQUEST']._serialized_start=458
  _globals['_CONNECTREQUEST']._serialized_end=491
  _globals['_CHATEVENT']._serialized_start=493
  _globals['_CHATEVENT']._serialized_end=593
  _globals['_MESSAGEEVENT']._serialized_start=595
  _globals['_MESSAGEEVENT']._serialized_end=710
  _globals['_PRESENCEEVENT']._serialized_start=712
  _globals['_PRESENCEEVENT']._serialized_end=814
  _globals['_PRESENCEEVENT_TYPE']._serialized_start=786
  _globals['_PRESENCEEVENT_TYPE']._serialized_end=814
  _globals['_CHATSERVICE']._serialized_start=817
  _globals['_CHATSERVICE']._serialized_end=1015
# @@protoc_insertion_point(module_scope)
