// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: proto/storage/analysis.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Analysis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Score         float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	At            *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=at,proto3" json:"at,omitempty"`
	Version       string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Analysis) Reset() {
	*x = Analysis{}
	mi := &file_proto_storage_analysis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Analysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Analysis) ProtoMessage() {}

func (x *Analysis) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_analysis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Analysis.ProtoReflect.Descriptor instead.
func (*Analysis) Descriptor() ([]byte, []int) {
	return file_proto_storage_analysis_proto_rawDescGZIP(), []int{0}
}

func (x *Analysis) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Analysis) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Analysis) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Analysis) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Analysis) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

func (x *Analysis) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_proto_storage_analysis_proto protoreflect.FileDescriptor

const file_proto_storage_analysis_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/storage/analysis.proto\x12\rmessage.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaf\x01\n" +
	"\bAnalysis\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\x12*\n" +
	"\x02at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversionB\x19Z\x17analysis/proto/pb-go;pbb\x06proto3"

var (
	file_proto_storage_analysis_proto_rawDescOnce sync.Once
	file_proto_storage_analysis_proto_rawDescData []byte
)

func file_proto_storage_analysis_proto_rawDescGZIP() []byte {
	file_proto_storage_analysis_proto_rawDescOnce.Do(func() {
		file_proto_storage_analysis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_storage_analysis_proto_rawDesc), len(file_proto_storage_analysis_proto_rawDesc)))
	})
	return file_proto_storage_analysis_proto_rawDescData
}

var file_proto_storage_analysis_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_storage_analysis_proto_goTypes = []any{
	(*Analysis)(nil),              // 0: message.proto.Analysis
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_proto_storage_analysis_proto_depIdxs = []int32{
	1, // 0: message.proto.Analysis.at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_storage_analysis_proto_init() }
func file_proto_storage_analysis_proto_init() {
	if File_proto_storage_analysis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_storage_analysis_proto_rawDesc), len(file_proto_storage_analysis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_storage_analysis_proto_goTypes,
		DependencyIndexes: file_proto_storage_analysis_proto_depIdxs,
		MessageInfos:      file_proto_storage_analysis_proto_msgTypes,
	}.Build()
	File_proto_storage_analysis_proto = out.File
	file_proto_storage_analysis_proto_goTypes = nil
	file_proto_storage_analysis_proto_depIdxs = nil
}
