// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: proto/storage/file_task.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Priority int32

const (
	Priority_HIGH   Priority = 0
	Priority_NORMAL Priority = 1
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "HIGH",
		1: "NORMAL",
	}
	Priority_value = map[string]int32{
		"HIGH":   0,
		"NORMAL": 1,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_storage_file_task_proto_enumTypes[0].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_proto_storage_file_task_proto_enumTypes[0]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_proto_storage_file_task_proto_rawDescGZIP(), []int{0}
}

type FileTask struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Path              string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	RawMimeType       string                 `protobuf:"bytes,3,opt,name=raw_mime_type,json=rawMimeType,proto3" json:"raw_mime_type,omitempty"`
	EffectiveMimeType string                 `protobuf:"bytes,4,opt,name=effective_mime_type,json=effectiveMimeType,proto3" json:"effective_mime_type,omitempty"`
	Size              uint64                 `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	Prior             Priority               `protobuf:"varint,6,opt,name=prior,proto3,enum=storage.Priority" json:"prior,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	RetryCount        int32                  `protobuf:"varint,8,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FileTask) Reset() {
	*x = FileTask{}
	mi := &file_proto_storage_file_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileTask) ProtoMessage() {}

func (x *FileTask) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_file_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileTask.ProtoReflect.Descriptor instead.
func (*FileTask) Descriptor() ([]byte, []int) {
	return file_proto_storage_file_task_proto_rawDescGZIP(), []int{0}
}

func (x *FileTask) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FileTask) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileTask) GetRawMimeType() string {
	if x != nil {
		return x.RawMimeType
	}
	return ""
}

func (x *FileTask) GetEffectiveMimeType() string {
	if x != nil {
		return x.EffectiveMimeType
	}
	return ""
}

func (x *FileTask) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileTask) GetPrior() Priority {
	if x != nil {
		return x.Prior
	}
	return Priority_HIGH
}

func (x *FileTask) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *FileTask) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

var File_proto_storage_file_task_proto protoreflect.FileDescriptor

const file_proto_storage_file_task_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/storage/file_task.proto\x12\astorage\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9b\x02\n" +
	"\bFileTask\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\"\n" +
	"\rraw_mime_type\x18\x03 \x01(\tR\vrawMimeType\x12.\n" +
	"\x13effective_mime_type\x18\x04 \x01(\tR\x11effectiveMimeType\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x04R\x04size\x12'\n" +
	"\x05prior\x18\x06 \x01(\x0e2\x11.storage.PriorityR\x05prior\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1f\n" +
	"\vretry_count\x18\b \x01(\x05R\n" +
	"retryCount* \n" +
	"\bPriority\x12\b\n" +
	"\x04HIGH\x10\x00\x12\n" +
	"\n" +
	"\x06NORMAL\x10\x01B\x06Z\x04./pbb\x06proto3"

var (
	file_proto_storage_file_task_proto_rawDescOnce sync.Once
	file_proto_storage_file_task_proto_rawDescData []byte
)

func file_proto_storage_file_task_proto_rawDescGZIP() []byte {
	file_proto_storage_file_task_proto_rawDescOnce.Do(func() {
		file_proto_storage_file_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_storage_file_task_proto_rawDesc), len(file_proto_storage_file_task_proto_rawDesc)))
	})
	return file_proto_storage_file_task_proto_rawDescData
}

var file_proto_storage_file_task_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_storage_file_task_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_storage_file_task_proto_goTypes = []any{
	(Priority)(0),                 // 0: storage.Priority
	(*FileTask)(nil),              // 1: storage.FileTask
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_proto_storage_file_task_proto_depIdxs = []int32{
	0, // 0: storage.FileTask.prior:type_name -> storage.Priority
	2, // 1: storage.FileTask.created_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_storage_file_task_proto_init() }
func file_proto_storage_file_task_proto_init() {
	if File_proto_storage_file_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_storage_file_task_proto_rawDesc), len(file_proto_storage_file_task_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_storage_file_task_proto_goTypes,
		DependencyIndexes: file_proto_storage_file_task_proto_depIdxs,
		EnumInfos:         file_proto_storage_file_task_proto_enumTypes,
		MessageInfos:      file_proto_storage_file_task_proto_msgTypes,
	}.Build()
	File_proto_storage_file_task_proto = out.File
	file_proto_storage_file_task_proto_goTypes = nil
	file_proto_storage_file_task_proto_depIdxs = nil
}
