// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: proto/storage/message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Room          int64                  `protobuf:"varint,2,opt,name=room,proto3" json:"room,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	At            *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=at,proto3" json:"at,omitempty"`
	ToxicityScore float64                `protobuf:"fixed64,6,opt,name=toxicity_score,json=toxicityScore,proto3" json:"toxicity_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_storage_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_storage_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetRoom() int64 {
	if x != nil {
		return x.Room
	}
	return 0
}

func (x *Message) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

func (x *Message) GetToxicityScore() float64 {
	if x != nil {
		return x.ToxicityScore
	}
	return 0
}

var File_proto_storage_message_proto protoreflect.FileDescriptor

const file_proto_storage_message_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/storage/message.proto\x12\rmessage.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb2\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04room\x18\x02 \x01(\x03R\x04room\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12*\n" +
	"\x02at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\x12%\n" +
	"\x0etoxicity_score\x18\x06 \x01(\x01R\rtoxicityScoreB\x19Z\x17messages/proto/pb-go;pbb\x06proto3"

var (
	file_proto_storage_message_proto_rawDescOnce sync.Once
	file_proto_storage_message_proto_rawDescData []byte
)

func file_proto_storage_message_proto_rawDescGZIP() []byte {
	file_proto_storage_message_proto_rawDescOnce.Do(func() {
		file_proto_storage_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_storage_message_proto_rawDesc), len(file_proto_storage_message_proto_rawDesc)))
	})
	return file_proto_storage_message_proto_rawDescData
}

var file_proto_storage_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_storage_message_proto_goTypes = []any{
	(*Message)(nil),               // 0: message.proto.Message
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_proto_storage_message_proto_depIdxs = []int32{
	1, // 0: message.proto.Message.at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_storage_message_proto_init() }
func file_proto_storage_message_proto_init() {
	if File_proto_storage_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_storage_message_proto_rawDesc), len(file_proto_storage_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_storage_message_proto_goTypes,
		DependencyIndexes: file_proto_storage_message_proto_depIdxs,
		MessageInfos:      file_proto_storage_message_proto_msgTypes,
	}.Build()
	File_proto_storage_message_proto = out.File
	file_proto_storage_message_proto_goTypes = nil
	file_proto_storage_message_proto_depIdxs = nil
}
