// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=../mocks/mock_contract.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	contract "chat-lab/contract"
	chat "chat-lab/domain/chat"
	specialist "chat-lab/domain/specialist"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockISupervisor is a mock of ISupervisor interface.
type MockISupervisor struct {
	ctrl     *gomock.Controller
	recorder *MockISupervisorMockRecorder
	isgomock struct{}
}

// MockISupervisorMockRecorder is the mock recorder for MockISupervisor.
type MockISupervisorMockRecorder struct {
	mock *MockISupervisor
}

// NewMockISupervisor creates a new mock instance.
func NewMockISupervisor(ctrl *gomock.Controller) *MockISupervisor {
	mock := &MockISupervisor{ctrl: ctrl}
	mock.recorder = &MockISupervisorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISupervisor) EXPECT() *MockISupervisorMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockISupervisor) Add(worker ...contract.Worker) contract.ISupervisor {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range worker {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Add", varargs...)
	ret0, _ := ret[0].(contract.ISupervisor)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockISupervisorMockRecorder) Add(worker ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockISupervisor)(nil).Add), worker...)
}

// Run mocks base method.
func (m *MockISupervisor) Run(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Run", ctx)
}

// Run indicates an expected call of Run.
func (mr *MockISupervisorMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockISupervisor)(nil).Run), ctx)
}

// Start mocks base method.
func (m *MockISupervisor) Start(ctx context.Context, worker contract.Worker) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start", ctx, worker)
}

// Start indicates an expected call of Start.
func (mr *MockISupervisorMockRecorder) Start(ctx, worker any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockISupervisor)(nil).Start), ctx, worker)
}

// Stop mocks base method.
func (m *MockISupervisor) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockISupervisorMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockISupervisor)(nil).Stop))
}

// MockWorker is a mock of Worker interface.
type MockWorker struct {
	ctrl     *gomock.Controller
	recorder *MockWorkerMockRecorder
	isgomock struct{}
}

// MockWorkerMockRecorder is the mock recorder for MockWorker.
type MockWorkerMockRecorder struct {
	mock *MockWorker
}

// NewMockWorker creates a new mock instance.
func NewMockWorker(ctrl *gomock.Controller) *MockWorker {
	mock := &MockWorker{ctrl: ctrl}
	mock.recorder = &MockWorkerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorker) EXPECT() *MockWorkerMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockWorker) Run(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockWorkerMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockWorker)(nil).Run), ctx)
}

// MockFileAnalyzerEvent is a mock of FileAnalyzerEvent interface.
type MockFileAnalyzerEvent struct {
	ctrl     *gomock.Controller
	recorder *MockFileAnalyzerEventMockRecorder
	isgomock struct{}
}

// MockFileAnalyzerEventMockRecorder is the mock recorder for MockFileAnalyzerEvent.
type MockFileAnalyzerEventMockRecorder struct {
	mock *MockFileAnalyzerEvent
}

// NewMockFileAnalyzerEvent creates a new mock instance.
func NewMockFileAnalyzerEvent(ctrl *gomock.Controller) *MockFileAnalyzerEvent {
	mock := &MockFileAnalyzerEvent{ctrl: ctrl}
	mock.recorder = &MockFileAnalyzerEventMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileAnalyzerEvent) EXPECT() *MockFileAnalyzerEventMockRecorder {
	return m.recorder
}

// Namespace mocks base method.
func (m *MockFileAnalyzerEvent) Namespace() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Namespace")
	ret0, _ := ret[0].(string)
	return ret0
}

// Namespace indicates an expected call of Namespace.
func (mr *MockFileAnalyzerEventMockRecorder) Namespace() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Namespace", reflect.TypeOf((*MockFileAnalyzerEvent)(nil).Namespace))
}

// MockDomainEvent is a mock of DomainEvent interface.
type MockDomainEvent struct {
	ctrl     *gomock.Controller
	recorder *MockDomainEventMockRecorder
	isgomock struct{}
}

// MockDomainEventMockRecorder is the mock recorder for MockDomainEvent.
type MockDomainEventMockRecorder struct {
	mock *MockDomainEvent
}

// NewMockDomainEvent creates a new mock instance.
func NewMockDomainEvent(ctrl *gomock.Controller) *MockDomainEvent {
	mock := &MockDomainEvent{ctrl: ctrl}
	mock.recorder = &MockDomainEventMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDomainEvent) EXPECT() *MockDomainEventMockRecorder {
	return m.recorder
}

// RoomID mocks base method.
func (m *MockDomainEvent) RoomID() chat.RoomID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RoomID")
	ret0, _ := ret[0].(chat.RoomID)
	return ret0
}

// RoomID indicates an expected call of RoomID.
func (mr *MockDomainEventMockRecorder) RoomID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoomID", reflect.TypeOf((*MockDomainEvent)(nil).RoomID))
}

// MockEventSink is a mock of EventSink interface.
type MockEventSink[E any] struct {
	ctrl     *gomock.Controller
	recorder *MockEventSinkMockRecorder[E]
	isgomock struct{}
}

// MockEventSinkMockRecorder is the mock recorder for MockEventSink.
type MockEventSinkMockRecorder[E any] struct {
	mock *MockEventSink[E]
}

// NewMockEventSink creates a new mock instance.
func NewMockEventSink[E any](ctrl *gomock.Controller) *MockEventSink[E] {
	mock := &MockEventSink[E]{ctrl: ctrl}
	mock.recorder = &MockEventSinkMockRecorder[E]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventSink[E]) EXPECT() *MockEventSinkMockRecorder[E] {
	return m.recorder
}

// Consume mocks base method.
func (m *MockEventSink[E]) Consume(ctx context.Context, e E) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consume", ctx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// Consume indicates an expected call of Consume.
func (mr *MockEventSinkMockRecorder[E]) Consume(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockEventSink[E])(nil).Consume), ctx, e)
}

// MockIRegistry is a mock of IRegistry interface.
type MockIRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockIRegistryMockRecorder
	isgomock struct{}
}

// MockIRegistryMockRecorder is the mock recorder for MockIRegistry.
type MockIRegistryMockRecorder struct {
	mock *MockIRegistry
}

// NewMockIRegistry creates a new mock instance.
func NewMockIRegistry(ctrl *gomock.Controller) *MockIRegistry {
	mock := &MockIRegistry{ctrl: ctrl}
	mock.recorder = &MockIRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRegistry) EXPECT() *MockIRegistryMockRecorder {
	return m.recorder
}

// GetSinksForRoom mocks base method.
func (m *MockIRegistry) GetSinksForRoom(roomID chat.RoomID) []contract.EventSink[contract.DomainEvent] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSinksForRoom", roomID)
	ret0, _ := ret[0].([]contract.EventSink[contract.DomainEvent])
	return ret0
}

// GetSinksForRoom indicates an expected call of GetSinksForRoom.
func (mr *MockIRegistryMockRecorder) GetSinksForRoom(roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSinksForRoom", reflect.TypeOf((*MockIRegistry)(nil).GetSinksForRoom), roomID)
}

// Subscribe mocks base method.
func (m *MockIRegistry) Subscribe(participantID string, roomID chat.RoomID, sink contract.EventSink[contract.DomainEvent]) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Subscribe", participantID, roomID, sink)
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockIRegistryMockRecorder) Subscribe(participantID, roomID, sink any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockIRegistry)(nil).Subscribe), participantID, roomID, sink)
}

// Unsubscribe mocks base method.
func (m *MockIRegistry) Unsubscribe(participantID string, roomID chat.RoomID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unsubscribe", participantID, roomID)
}

// Unsubscribe indicates an expected call of Unsubscribe.
func (mr *MockIRegistryMockRecorder) Unsubscribe(participantID, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockIRegistry)(nil).Unsubscribe), participantID, roomID)
}

// MockIOrchestrator is a mock of IOrchestrator interface.
type MockIOrchestrator struct {
	ctrl     *gomock.Controller
	recorder *MockIOrchestratorMockRecorder
	isgomock struct{}
}

// MockIOrchestratorMockRecorder is the mock recorder for MockIOrchestrator.
type MockIOrchestratorMockRecorder struct {
	mock *MockIOrchestrator
}

// NewMockIOrchestrator creates a new mock instance.
func NewMockIOrchestrator(ctrl *gomock.Controller) *MockIOrchestrator {
	mock := &MockIOrchestrator{ctrl: ctrl}
	mock.recorder = &MockIOrchestratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIOrchestrator) EXPECT() *MockIOrchestratorMockRecorder {
	return m.recorder
}

// GetMessages mocks base method.
func (m *MockIOrchestrator) GetMessages(cmd chat.GetMessageCommand) ([]chat.Message, *string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessages", cmd)
	ret0, _ := ret[0].([]chat.Message)
	ret1, _ := ret[1].(*string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetMessages indicates an expected call of GetMessages.
func (mr *MockIOrchestratorMockRecorder) GetMessages(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessages", reflect.TypeOf((*MockIOrchestrator)(nil).GetMessages), cmd)
}

// PostMessage mocks base method.
func (m *MockIOrchestrator) PostMessage(ctx context.Context, cmd chat.PostMessageCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostMessage", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// PostMessage indicates an expected call of PostMessage.
func (mr *MockIOrchestratorMockRecorder) PostMessage(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostMessage", reflect.TypeOf((*MockIOrchestrator)(nil).PostMessage), ctx, cmd)
}

// RegisterParticipant mocks base method.
func (m *MockIOrchestrator) RegisterParticipant(pID string, roomID chat.RoomID, sink contract.EventSink[contract.DomainEvent]) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterParticipant", pID, roomID, sink)
}

// RegisterParticipant indicates an expected call of RegisterParticipant.
func (mr *MockIOrchestratorMockRecorder) RegisterParticipant(pID, roomID, sink any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterParticipant", reflect.TypeOf((*MockIOrchestrator)(nil).RegisterParticipant), pID, roomID, sink)
}

// RegisterRoom mocks base method.
func (m *MockIOrchestrator) RegisterRoom(room *chat.Room) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterRoom", room)
}

// RegisterRoom indicates an expected call of RegisterRoom.
func (mr *MockIOrchestratorMockRecorder) RegisterRoom(room any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterRoom", reflect.TypeOf((*MockIOrchestrator)(nil).RegisterRoom), room)
}

// Start mocks base method.
func (m *MockIOrchestrator) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockIOrchestratorMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockIOrchestrator)(nil).Start), ctx)
}

// Stop mocks base method.
func (m *MockIOrchestrator) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockIOrchestratorMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockIOrchestrator)(nil).Stop))
}

// UnregisterParticipant mocks base method.
func (m *MockIOrchestrator) UnregisterParticipant(pID string, roomID chat.RoomID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UnregisterParticipant", pID, roomID)
}

// UnregisterParticipant indicates an expected call of UnregisterParticipant.
func (mr *MockIOrchestratorMockRecorder) UnregisterParticipant(pID, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnregisterParticipant", reflect.TypeOf((*MockIOrchestrator)(nil).UnregisterParticipant), pID, roomID)
}

// MockSpecialistCoordinator is a mock of SpecialistCoordinator interface.
type MockSpecialistCoordinator struct {
	ctrl     *gomock.Controller
	recorder *MockSpecialistCoordinatorMockRecorder
	isgomock struct{}
}

// MockSpecialistCoordinatorMockRecorder is the mock recorder for MockSpecialistCoordinator.
type MockSpecialistCoordinatorMockRecorder struct {
	mock *MockSpecialistCoordinator
}

// NewMockSpecialistCoordinator creates a new mock instance.
func NewMockSpecialistCoordinator(ctrl *gomock.Controller) *MockSpecialistCoordinator {
	mock := &MockSpecialistCoordinator{ctrl: ctrl}
	mock.recorder = &MockSpecialistCoordinatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpecialistCoordinator) EXPECT() *MockSpecialistCoordinatorMockRecorder {
	return m.recorder
}

// Broadcast mocks base method.
func (m *MockSpecialistCoordinator) Broadcast(ctx context.Context, req specialist.AnalysisRequest) (specialist.AnalysisResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Broadcast", ctx, req)
	ret0, _ := ret[0].(specialist.AnalysisResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Broadcast indicates an expected call of Broadcast.
func (mr *MockSpecialistCoordinatorMockRecorder) Broadcast(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Broadcast", reflect.TypeOf((*MockSpecialistCoordinator)(nil).Broadcast), ctx, req)
}

// MockISpecialistClient is a mock of ISpecialistClient interface.
type MockISpecialistClient struct {
	ctrl     *gomock.Controller
	recorder *MockISpecialistClientMockRecorder
	isgomock struct{}
}

// MockISpecialistClientMockRecorder is the mock recorder for MockISpecialistClient.
type MockISpecialistClientMockRecorder struct {
	mock *MockISpecialistClient
}

// NewMockISpecialistClient creates a new mock instance.
func NewMockISpecialistClient(ctrl *gomock.Controller) *MockISpecialistClient {
	mock := &MockISpecialistClient{ctrl: ctrl}
	mock.recorder = &MockISpecialistClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISpecialistClient) EXPECT() *MockISpecialistClientMockRecorder {
	return m.recorder
}

// Analyze mocks base method.
func (m *MockISpecialistClient) Analyze(ctx context.Context, request specialist.Request) (specialist.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Analyze", ctx, request)
	ret0, _ := ret[0].(specialist.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Analyze indicates an expected call of Analyze.
func (mr *MockISpecialistClientMockRecorder) Analyze(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Analyze", reflect.TypeOf((*MockISpecialistClient)(nil).Analyze), ctx, request)
}
