// Code generated by MockGen. DO NOT EDIT.
// Source: file_analyzer.go
//
// Generated by this command:
//
//	mockgen -source=file_analyzer.go -destination=../../../mocks/mock_file_analyzer.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	client "chat-lab/infrastructure/grpc/client"
	analyzer "chat-lab/proto/analyzer"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFileAnalyzerClient is a mock of FileAnalyzerClient interface.
type MockFileAnalyzerClient struct {
	ctrl     *gomock.Controller
	recorder *MockFileAnalyzerClientMockRecorder
	isgomock struct{}
}

// MockFileAnalyzerClientMockRecorder is the mock recorder for MockFileAnalyzerClient.
type MockFileAnalyzerClientMockRecorder struct {
	mock *MockFileAnalyzerClient
}

// NewMockFileAnalyzerClient creates a new mock instance.
func NewMockFileAnalyzerClient(ctrl *gomock.Controller) *MockFileAnalyzerClient {
	mock := &MockFileAnalyzerClient{ctrl: ctrl}
	mock.recorder = &MockFileAnalyzerClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileAnalyzerClient) EXPECT() *MockFileAnalyzerClientMockRecorder {
	return m.recorder
}

// Analyze mocks base method.
func (m *MockFileAnalyzerClient) Analyze(ctx context.Context) (client.FileAnalyzerStream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Analyze", ctx)
	ret0, _ := ret[0].(client.FileAnalyzerStream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Analyze indicates an expected call of Analyze.
func (mr *MockFileAnalyzerClientMockRecorder) Analyze(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Analyze", reflect.TypeOf((*MockFileAnalyzerClient)(nil).Analyze), ctx)
}

// MockFileAnalyzerStream is a mock of FileAnalyzerStream interface.
type MockFileAnalyzerStream struct {
	ctrl     *gomock.Controller
	recorder *MockFileAnalyzerStreamMockRecorder
	isgomock struct{}
}

// MockFileAnalyzerStreamMockRecorder is the mock recorder for MockFileAnalyzerStream.
type MockFileAnalyzerStreamMockRecorder struct {
	mock *MockFileAnalyzerStream
}

// NewMockFileAnalyzerStream creates a new mock instance.
func NewMockFileAnalyzerStream(ctrl *gomock.Controller) *MockFileAnalyzerStream {
	mock := &MockFileAnalyzerStream{ctrl: ctrl}
	mock.recorder = &MockFileAnalyzerStreamMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileAnalyzerStream) EXPECT() *MockFileAnalyzerStreamMockRecorder {
	return m.recorder
}

// CloseAndRecv mocks base method.
func (m *MockFileAnalyzerStream) CloseAndRecv() (*analyzer.FileAnalyzerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseAndRecv")
	ret0, _ := ret[0].(*analyzer.FileAnalyzerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CloseAndRecv indicates an expected call of CloseAndRecv.
func (mr *MockFileAnalyzerStreamMockRecorder) CloseAndRecv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseAndRecv", reflect.TypeOf((*MockFileAnalyzerStream)(nil).CloseAndRecv))
}

// CloseSend mocks base method.
func (m *MockFileAnalyzerStream) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockFileAnalyzerStreamMockRecorder) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockFileAnalyzerStream)(nil).CloseSend))
}

// Send mocks base method.
func (m *MockFileAnalyzerStream) Send(arg0 *analyzer.FileAnalyzerRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockFileAnalyzerStreamMockRecorder) Send(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockFileAnalyzerStream)(nil).Send), arg0)
}
