// Code generated by MockGen. DO NOT EDIT.
// Source: message.go
//
// Generated by this command:
//
//	mockgen -source=message.go -destination=../mocks/mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	repositories "chat-lab/repositories"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetMessages mocks base method.
func (m *MockRepository) GetMessages(room int, cursor *string) ([]repositories.DiskMessage, *string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessages", room, cursor)
	ret0, _ := ret[0].([]repositories.DiskMessage)
	ret1, _ := ret[1].(*string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetMessages indicates an expected call of GetMessages.
func (mr *MockRepositoryMockRecorder) GetMessages(room, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessages", reflect.TypeOf((*MockRepository)(nil).GetMessages), room, cursor)
}

// StoreMessage mocks base method.
func (m *MockRepository) StoreMessage(message repositories.DiskMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreMessage", message)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreMessage indicates an expected call of StoreMessage.
func (mr *MockRepositoryMockRecorder) StoreMessage(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreMessage", reflect.TypeOf((*MockRepository)(nil).StoreMessage), message)
}
