// Code generated by MockGen. DO NOT EDIT.
// Source: message.go
//
// Generated by this command:
//
//	mockgen -source=message.go -destination=../mocks/mock_message_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	repositories "chat-lab/infrastructure/storage"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIMessageRepository is a mock of IMessageRepository interface.
type MockIMessageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIMessageRepositoryMockRecorder
	isgomock struct{}
}

// MockIMessageRepositoryMockRecorder is the mock recorder for MockIMessageRepository.
type MockIMessageRepositoryMockRecorder struct {
	mock *MockIMessageRepository
}

// NewMockIMessageRepository creates a new mock instance.
func NewMockIMessageRepository(ctrl *gomock.Controller) *MockIMessageRepository {
	mock := &MockIMessageRepository{ctrl: ctrl}
	mock.recorder = &MockIMessageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIMessageRepository) EXPECT() *MockIMessageRepositoryMockRecorder {
	return m.recorder
}

// GetMessages mocks base method.
func (m *MockIMessageRepository) GetMessages(room int, cursor *string) ([]repositories.DiskMessage, *string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessages", room, cursor)
	ret0, _ := ret[0].([]repositories.DiskMessage)
	ret1, _ := ret[1].(*string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetMessages indicates an expected call of GetMessages.
func (mr *MockIMessageRepositoryMockRecorder) GetMessages(room, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessages", reflect.TypeOf((*MockIMessageRepository)(nil).GetMessages), room, cursor)
}

// StoreMessage mocks base method.
func (m *MockIMessageRepository) StoreMessage(message repositories.DiskMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreMessage", message)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreMessage indicates an expected call of StoreMessage.
func (mr *MockIMessageRepositoryMockRecorder) StoreMessage(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreMessage", reflect.TypeOf((*MockIMessageRepository)(nil).StoreMessage), message)
}
