// Code generated by MockGen. DO NOT EDIT.
// Source: file_task_repository.go
//
// Generated by this command:
//
//	mockgen -source=file_task_repository.go -destination=../../mocks/mock_file_task_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	storage "chat-lab/infrastructure/storage"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIFileTaskRepository is a mock of IFileTaskRepository interface.
type MockIFileTaskRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIFileTaskRepositoryMockRecorder
	isgomock struct{}
}

// MockIFileTaskRepositoryMockRecorder is the mock recorder for MockIFileTaskRepository.
type MockIFileTaskRepositoryMockRecorder struct {
	mock *MockIFileTaskRepository
}

// NewMockIFileTaskRepository creates a new mock instance.
func NewMockIFileTaskRepository(ctrl *gomock.Controller) *MockIFileTaskRepository {
	mock := &MockIFileTaskRepository{ctrl: ctrl}
	mock.recorder = &MockIFileTaskRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIFileTaskRepository) EXPECT() *MockIFileTaskRepositoryMockRecorder {
	return m.recorder
}

// EnqueueTask mocks base method.
func (m *MockIFileTaskRepository) EnqueueTask(task storage.FileTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueTask", task)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnqueueTask indicates an expected call of EnqueueTask.
func (mr *MockIFileTaskRepositoryMockRecorder) EnqueueTask(task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueTask", reflect.TypeOf((*MockIFileTaskRepository)(nil).EnqueueTask), task)
}

// GetNextBatch mocks base method.
func (m *MockIFileTaskRepository) GetNextBatch(i int) ([]storage.FileTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNextBatch", i)
	ret0, _ := ret[0].([]storage.FileTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNextBatch indicates an expected call of GetNextBatch.
func (mr *MockIFileTaskRepositoryMockRecorder) GetNextBatch(i any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNextBatch", reflect.TypeOf((*MockIFileTaskRepository)(nil).GetNextBatch), i)
}

// MarkAsProcessing mocks base method.
func (m *MockIFileTaskRepository) MarkAsProcessing(task storage.FileTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsProcessing", task)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsProcessing indicates an expected call of MarkAsProcessing.
func (mr *MockIFileTaskRepositoryMockRecorder) MarkAsProcessing(task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsProcessing", reflect.TypeOf((*MockIFileTaskRepository)(nil).MarkAsProcessing), task)
}
