// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=../mocks/mock_contract.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	contract "chat-lab/contract"
	event "chat-lab/domain/event"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockISupervisor is a mock of ISupervisor interface.
type MockISupervisor struct {
	ctrl     *gomock.Controller
	recorder *MockISupervisorMockRecorder
	isgomock struct{}
}

// MockISupervisorMockRecorder is the mock recorder for MockISupervisor.
type MockISupervisorMockRecorder struct {
	mock *MockISupervisor
}

// NewMockISupervisor creates a new mock instance.
func NewMockISupervisor(ctrl *gomock.Controller) *MockISupervisor {
	mock := &MockISupervisor{ctrl: ctrl}
	mock.recorder = &MockISupervisorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISupervisor) EXPECT() *MockISupervisorMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockISupervisor) Add(worker ...contract.Worker) contract.ISupervisor {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range worker {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Add", varargs...)
	ret0, _ := ret[0].(contract.ISupervisor)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockISupervisorMockRecorder) Add(worker ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockISupervisor)(nil).Add), worker...)
}

// Run mocks base method.
func (m *MockISupervisor) Run(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Run", ctx)
}

// Run indicates an expected call of Run.
func (mr *MockISupervisorMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockISupervisor)(nil).Run), ctx)
}

// Start mocks base method.
func (m *MockISupervisor) Start(ctx context.Context, worker contract.Worker) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start", ctx, worker)
}

// Start indicates an expected call of Start.
func (mr *MockISupervisorMockRecorder) Start(ctx, worker any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockISupervisor)(nil).Start), ctx, worker)
}

// Stop mocks base method.
func (m *MockISupervisor) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockISupervisorMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockISupervisor)(nil).Stop))
}

// MockWorker is a mock of Worker interface.
type MockWorker struct {
	ctrl     *gomock.Controller
	recorder *MockWorkerMockRecorder
	isgomock struct{}
}

// MockWorkerMockRecorder is the mock recorder for MockWorker.
type MockWorkerMockRecorder struct {
	mock *MockWorker
}

// NewMockWorker creates a new mock instance.
func NewMockWorker(ctrl *gomock.Controller) *MockWorker {
	mock := &MockWorker{ctrl: ctrl}
	mock.recorder = &MockWorkerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorker) EXPECT() *MockWorkerMockRecorder {
	return m.recorder
}

// GetName mocks base method.
func (m *MockWorker) GetName() contract.WorkerName {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(contract.WorkerName)
	return ret0
}

// GetName indicates an expected call of GetName.
func (mr *MockWorkerMockRecorder) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockWorker)(nil).GetName))
}

// Run mocks base method.
func (m *MockWorker) Run(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockWorkerMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockWorker)(nil).Run), ctx)
}

// WithName mocks base method.
func (m *MockWorker) WithName(name string) contract.Worker {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithName", name)
	ret0, _ := ret[0].(contract.Worker)
	return ret0
}

// WithName indicates an expected call of WithName.
func (mr *MockWorkerMockRecorder) WithName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithName", reflect.TypeOf((*MockWorker)(nil).WithName), name)
}

// MockEventSink is a mock of EventSink interface.
type MockEventSink struct {
	ctrl     *gomock.Controller
	recorder *MockEventSinkMockRecorder
	isgomock struct{}
}

// MockEventSinkMockRecorder is the mock recorder for MockEventSink.
type MockEventSinkMockRecorder struct {
	mock *MockEventSink
}

// NewMockEventSink creates a new mock instance.
func NewMockEventSink(ctrl *gomock.Controller) *MockEventSink {
	mock := &MockEventSink{ctrl: ctrl}
	mock.recorder = &MockEventSinkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventSink) EXPECT() *MockEventSinkMockRecorder {
	return m.recorder
}

// Consume mocks base method.
func (m *MockEventSink) Consume(e event.DomainEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Consume", e)
}

// Consume indicates an expected call of Consume.
func (mr *MockEventSinkMockRecorder) Consume(e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockEventSink)(nil).Consume), e)
}
