// Code generated by MockGen. DO NOT EDIT.
// Source: analysis.go
//
// Generated by this command:
//
//	mockgen -source=analysis.go -destination=../mocks/mock_analysis_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	repositories "chat-lab/repositories"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockIAnalysisRepository is a mock of IAnalysisRepository interface.
type MockIAnalysisRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIAnalysisRepositoryMockRecorder
	isgomock struct{}
}

// MockIAnalysisRepositoryMockRecorder is the mock recorder for MockIAnalysisRepository.
type MockIAnalysisRepositoryMockRecorder struct {
	mock *MockIAnalysisRepository
}

// NewMockIAnalysisRepository creates a new mock instance.
func NewMockIAnalysisRepository(ctrl *gomock.Controller) *MockIAnalysisRepository {
	mock := &MockIAnalysisRepository{ctrl: ctrl}
	mock.recorder = &MockIAnalysisRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAnalysisRepository) EXPECT() *MockIAnalysisRepositoryMockRecorder {
	return m.recorder
}

// GetAnalyses mocks base method.
func (m *MockIAnalysisRepository) GetAnalyses(roomID string, cursor *string) ([]repositories.Analysis, *string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAnalyses", roomID, cursor)
	ret0, _ := ret[0].([]repositories.Analysis)
	ret1, _ := ret[1].(*string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAnalyses indicates an expected call of GetAnalyses.
func (mr *MockIAnalysisRepositoryMockRecorder) GetAnalyses(roomID, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAnalyses", reflect.TypeOf((*MockIAnalysisRepository)(nil).GetAnalyses), roomID, cursor)
}

// GetByMessageId mocks base method.
func (m *MockIAnalysisRepository) GetByMessageId(roomID string, messageId uuid.UUID) (repositories.Analysis, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByMessageId", roomID, messageId)
	ret0, _ := ret[0].(repositories.Analysis)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByMessageId indicates an expected call of GetByMessageId.
func (mr *MockIAnalysisRepositoryMockRecorder) GetByMessageId(roomID, messageId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByMessageId", reflect.TypeOf((*MockIAnalysisRepository)(nil).GetByMessageId), roomID, messageId)
}

// Search mocks base method.
func (m *MockIAnalysisRepository) Search(query, roomID string) ([]repositories.Analysis, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", query, roomID)
	ret0, _ := ret[0].([]repositories.Analysis)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockIAnalysisRepositoryMockRecorder) Search(query, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockIAnalysisRepository)(nil).Search), query, roomID)
}

// Store mocks base method.
func (m *MockIAnalysisRepository) Store(analysis repositories.Analysis) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", analysis)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockIAnalysisRepositoryMockRecorder) Store(analysis any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockIAnalysisRepository)(nil).Store), analysis)
}

// StoreBatch mocks base method.
func (m *MockIAnalysisRepository) StoreBatch(analyses []repositories.Analysis) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreBatch", analyses)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreBatch indicates an expected call of StoreBatch.
func (mr *MockIAnalysisRepositoryMockRecorder) StoreBatch(analyses any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreBatch", reflect.TypeOf((*MockIAnalysisRepository)(nil).StoreBatch), analyses)
}
