// Code generated by MockGen. DO NOT EDIT.
// Source: analysis.go
//
// Generated by this command:
//
//	mockgen -source=analysis.go -destination=../mocks/mock_analysis_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	repositories "chat-lab/infrastructure/storage"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockIAnalysisRepository is a mock of IAnalysisRepository interface.
type MockIAnalysisRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIAnalysisRepositoryMockRecorder
	isgomock struct{}
}

// MockIAnalysisRepositoryMockRecorder is the mock recorder for MockIAnalysisRepository.
type MockIAnalysisRepositoryMockRecorder struct {
	mock *MockIAnalysisRepository
}

// NewMockIAnalysisRepository creates a new mock instance.
func NewMockIAnalysisRepository(ctrl *gomock.Controller) *MockIAnalysisRepository {
	mock := &MockIAnalysisRepository{ctrl: ctrl}
	mock.recorder = &MockIAnalysisRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAnalysisRepository) EXPECT() *MockIAnalysisRepositoryMockRecorder {
	return m.recorder
}

// DeleteByMessageId mocks base method.
func (m *MockIAnalysisRepository) DeleteByMessageId(roomID string, messageId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByMessageId", roomID, messageId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByMessageId indicates an expected call of DeleteByMessageId.
func (mr *MockIAnalysisRepositoryMockRecorder) DeleteByMessageId(roomID, messageId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByMessageId", reflect.TypeOf((*MockIAnalysisRepository)(nil).DeleteByMessageId), roomID, messageId)
}

// FetchFullByMessageId mocks base method.
func (m *MockIAnalysisRepository) FetchFullByMessageId(roomID string, messageId uuid.UUID) (repositories.Analysis, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchFullByMessageId", roomID, messageId)
	ret0, _ := ret[0].(repositories.Analysis)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchFullByMessageId indicates an expected call of FetchFullByMessageId.
func (mr *MockIAnalysisRepositoryMockRecorder) FetchFullByMessageId(roomID, messageId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchFullByMessageId", reflect.TypeOf((*MockIAnalysisRepository)(nil).FetchFullByMessageId), roomID, messageId)
}

// Flush mocks base method.
func (m *MockIAnalysisRepository) Flush() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush")
	ret0, _ := ret[0].(error)
	return ret0
}

// Flush indicates an expected call of Flush.
func (mr *MockIAnalysisRepositoryMockRecorder) Flush() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockIAnalysisRepository)(nil).Flush))
}

// ScanAnalysesByRoom mocks base method.
func (m *MockIAnalysisRepository) ScanAnalysesByRoom(roomID string, cursor *string) ([]repositories.Analysis, *string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScanAnalysesByRoom", roomID, cursor)
	ret0, _ := ret[0].([]repositories.Analysis)
	ret1, _ := ret[1].(*string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ScanAnalysesByRoom indicates an expected call of ScanAnalysesByRoom.
func (mr *MockIAnalysisRepositoryMockRecorder) ScanAnalysesByRoom(roomID, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScanAnalysesByRoom", reflect.TypeOf((*MockIAnalysisRepository)(nil).ScanAnalysesByRoom), roomID, cursor)
}

// SearchByScoreRange mocks base method.
func (m *MockIAnalysisRepository) SearchByScoreRange(ctx context.Context, scoreName string, min, max float64, roomID string) ([]repositories.Analysis, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchByScoreRange", ctx, scoreName, min, max, roomID)
	ret0, _ := ret[0].([]repositories.Analysis)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchByScoreRange indicates an expected call of SearchByScoreRange.
func (mr *MockIAnalysisRepositoryMockRecorder) SearchByScoreRange(ctx, scoreName, min, max, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchByScoreRange", reflect.TypeOf((*MockIAnalysisRepository)(nil).SearchByScoreRange), ctx, scoreName, min, max, roomID)
}

// SearchPaginated mocks base method.
func (m *MockIAnalysisRepository) SearchPaginated(ctx context.Context, query, roomID string, offset int) ([]repositories.Analysis, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchPaginated", ctx, query, roomID, offset)
	ret0, _ := ret[0].([]repositories.Analysis)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchPaginated indicates an expected call of SearchPaginated.
func (mr *MockIAnalysisRepositoryMockRecorder) SearchPaginated(ctx, query, roomID, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchPaginated", reflect.TypeOf((*MockIAnalysisRepository)(nil).SearchPaginated), ctx, query, roomID, offset)
}

// Store mocks base method.
func (m *MockIAnalysisRepository) Store(analysis repositories.Analysis) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", analysis)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockIAnalysisRepositoryMockRecorder) Store(analysis any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockIAnalysisRepository)(nil).Store), analysis)
}

// StoreBatch mocks base method.
func (m *MockIAnalysisRepository) StoreBatch(analyses []repositories.Analysis) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreBatch", analyses)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreBatch indicates an expected call of StoreBatch.
func (mr *MockIAnalysisRepositoryMockRecorder) StoreBatch(analyses any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreBatch", reflect.TypeOf((*MockIAnalysisRepository)(nil).StoreBatch), analyses)
}
