// Code generated by MockGen. DO NOT EDIT.
// Source: analysis.go
//
// Generated by this command:
//
//	mockgen -source=analysis.go -destination=../mocks/mock_analysis_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	repositories "chat-lab/repositories"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIAnalysisRepository is a mock of IAnalysisRepository interface.
type MockIAnalysisRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIAnalysisRepositoryMockRecorder
	isgomock struct{}
}

// MockIAnalysisRepositoryMockRecorder is the mock recorder for MockIAnalysisRepository.
type MockIAnalysisRepositoryMockRecorder struct {
	mock *MockIAnalysisRepository
}

// NewMockIAnalysisRepository creates a new mock instance.
func NewMockIAnalysisRepository(ctrl *gomock.Controller) *MockIAnalysisRepository {
	mock := &MockIAnalysisRepository{ctrl: ctrl}
	mock.recorder = &MockIAnalysisRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAnalysisRepository) EXPECT() *MockIAnalysisRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockIAnalysisRepository) Get() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockIAnalysisRepositoryMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIAnalysisRepository)(nil).Get))
}

// Store mocks base method.
func (m *MockIAnalysisRepository) Store(analysis repositories.Analysis) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", analysis)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockIAnalysisRepositoryMockRecorder) Store(analysis any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockIAnalysisRepository)(nil).Store), analysis)
}
