# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/specialist/specialist_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/specialist/specialist_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)proto/specialist/specialist_service.proto\x12\x08\x61nalysis\"U\n\x11SpecialistRequest\x12&\n\x08metadata\x18\x01 \x01(\x0b\x32\x12.analysis.MetadataH\x00\x12\x0f\n\x05\x63hunk\x18\x02 \x01(\x0cH\x00\x42\x07\n\x05\x65ntry\"D\n\x08Metadata\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x11\n\tfile_name\x18\x02 \x01(\t\x12\x11\n\tmime_type\x18\x03 \x01(\t\"s\n\x12SpecialistResponse\x12/\n\rdocument_data\x18\x01 \x01(\x0b\x32\x16.analysis.DocumentDataH\x00\x12 \n\x05score\x18\x02 \x01(\x0b\x32\x0f.analysis.ScoreH\x00\x42\n\n\x08response\"%\n\x05Score\x12\r\n\x05score\x18\x01 \x01(\x01\x12\r\n\x05label\x18\x02 \x01(\t\"r\n\x0c\x44ocumentData\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\x12\n\npage_count\x18\x03 \x01(\x05\x12\x10\n\x08language\x18\x04 \x01(\t\x12\x1d\n\x05pages\x18\x05 \x03(\x0b\x32\x0e.analysis.Page\"\'\n\x04Page\x12\x0e\n\x06number\x18\x01 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t2a\n\x11SpecialistService\x12L\n\rAnalyzeStream\x12\x1b.analysis.SpecialistRequest\x1a\x1c.analysis.SpecialistResponse(\x01\x42\x06Z\x04./pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.specialist.specialist_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004./pb'
  _globals['_SPECIALISTREQUEST']._serialized_start=55
  _globals['_SPECIALISTREQUEST']._serialized_end=140
  _globals['_METADATA']._serialized_start=142
  _globals['_METADATA']._serialized_end=210
  _globals['_SPECIALISTRESPONSE']._serialized_start=212
  _globals['_SPECIALISTRESPONSE']._serialized_end=327
  _globals['_SCORE']._serialized_start=329
  _globals['_SCORE']._serialized_end=366
  _globals['_DOCUMENTDATA']._serialized_start=368
  _globals['_DOCUMENTDATA']._serialized_end=482
  _globals['_PAGE']._serialized_start=484
  _globals['_PAGE']._serialized_end=523
  _globals['_SPECIALISTSERVICE']._serialized_start=525
  _globals['_SPECIALISTSERVICE']._serialized_end=622
# @@protoc_insertion_point(module_scope)
