// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: proto/specialist/specialist_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpecialistRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Entry:
	//
	//	*SpecialistRequest_Metadata
	//	*SpecialistRequest_Chunk
	Entry         isSpecialistRequest_Entry `protobuf_oneof:"entry"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpecialistRequest) Reset() {
	*x = SpecialistRequest{}
	mi := &file_proto_specialist_specialist_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecialistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecialistRequest) ProtoMessage() {}

func (x *SpecialistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_specialist_specialist_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecialistRequest.ProtoReflect.Descriptor instead.
func (*SpecialistRequest) Descriptor() ([]byte, []int) {
	return file_proto_specialist_specialist_service_proto_rawDescGZIP(), []int{0}
}

func (x *SpecialistRequest) GetEntry() isSpecialistRequest_Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *SpecialistRequest) GetMetadata() *Metadata {
	if x != nil {
		if x, ok := x.Entry.(*SpecialistRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *SpecialistRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Entry.(*SpecialistRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isSpecialistRequest_Entry interface {
	isSpecialistRequest_Entry()
}

type SpecialistRequest_Metadata struct {
	Metadata *Metadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type SpecialistRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*SpecialistRequest_Metadata) isSpecialistRequest_Entry() {}

func (*SpecialistRequest_Chunk) isSpecialistRequest_Entry() {}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	MimeType      string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_proto_specialist_specialist_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_specialist_specialist_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_proto_specialist_specialist_service_proto_rawDescGZIP(), []int{1}
}

func (x *Metadata) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Metadata) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *Metadata) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

// Response from the Specialist binary (m2cgen transpiled code)
type SpecialistResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*SpecialistResponse_DocumentData
	//	*SpecialistResponse_Score
	Response      isSpecialistResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpecialistResponse) Reset() {
	*x = SpecialistResponse{}
	mi := &file_proto_specialist_specialist_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecialistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecialistResponse) ProtoMessage() {}

func (x *SpecialistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_specialist_specialist_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecialistResponse.ProtoReflect.Descriptor instead.
func (*SpecialistResponse) Descriptor() ([]byte, []int) {
	return file_proto_specialist_specialist_service_proto_rawDescGZIP(), []int{2}
}

func (x *SpecialistResponse) GetResponse() isSpecialistResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *SpecialistResponse) GetDocumentData() *DocumentData {
	if x != nil {
		if x, ok := x.Response.(*SpecialistResponse_DocumentData); ok {
			return x.DocumentData
		}
	}
	return nil
}

func (x *SpecialistResponse) GetScore() *Score {
	if x != nil {
		if x, ok := x.Response.(*SpecialistResponse_Score); ok {
			return x.Score
		}
	}
	return nil
}

type isSpecialistResponse_Response interface {
	isSpecialistResponse_Response()
}

type SpecialistResponse_DocumentData struct {
	DocumentData *DocumentData `protobuf:"bytes,1,opt,name=document_data,json=documentData,proto3,oneof"`
}

type SpecialistResponse_Score struct {
	Score *Score `protobuf:"bytes,2,opt,name=score,proto3,oneof"`
}

func (*SpecialistResponse_DocumentData) isSpecialistResponse_Response() {}

func (*SpecialistResponse_Score) isSpecialistResponse_Response() {}

type Score struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         float64                `protobuf:"fixed64,1,opt,name=score,proto3" json:"score,omitempty"` // Probability score between 0.0 and 1.0
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`   // Human-readable verdict (e.g., "SPAM", "TOXIC")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Score) Reset() {
	*x = Score{}
	mi := &file_proto_specialist_specialist_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Score) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Score) ProtoMessage() {}

func (x *Score) ProtoReflect() protoreflect.Message {
	mi := &file_proto_specialist_specialist_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Score.ProtoReflect.Descriptor instead.
func (*Score) Descriptor() ([]byte, []int) {
	return file_proto_specialist_specialist_service_proto_rawDescGZIP(), []int{3}
}

func (x *Score) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Score) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type DocumentData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	PageCount     int32                  `protobuf:"varint,3,opt,name=page_count,json=pageCount,proto3" json:"page_count,omitempty"`
	Language      string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	Pages         []*Page                `protobuf:"bytes,5,rep,name=pages,proto3" json:"pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentData) Reset() {
	*x = DocumentData{}
	mi := &file_proto_specialist_specialist_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentData) ProtoMessage() {}

func (x *DocumentData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_specialist_specialist_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentData.ProtoReflect.Descriptor instead.
func (*DocumentData) Descriptor() ([]byte, []int) {
	return file_proto_specialist_specialist_service_proto_rawDescGZIP(), []int{4}
}

func (x *DocumentData) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DocumentData) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *DocumentData) GetPageCount() int32 {
	if x != nil {
		return x.PageCount
	}
	return 0
}

func (x *DocumentData) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *DocumentData) GetPages() []*Page {
	if x != nil {
		return x.Pages
	}
	return nil
}

type Page struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int32                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Page) Reset() {
	*x = Page{}
	mi := &file_proto_specialist_specialist_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_proto_specialist_specialist_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_proto_specialist_specialist_service_proto_rawDescGZIP(), []int{5}
}

func (x *Page) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Page) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_proto_specialist_specialist_service_proto protoreflect.FileDescriptor

const file_proto_specialist_specialist_service_proto_rawDesc = "" +
	"\n" +
	")proto/specialist/specialist_service.proto\x12\banalysis\"f\n" +
	"\x11SpecialistRequest\x120\n" +
	"\bmetadata\x18\x01 \x01(\v2\x12.analysis.MetadataH\x00R\bmetadata\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\a\n" +
	"\x05entry\"c\n" +
	"\bMetadata\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\"\x88\x01\n" +
	"\x12SpecialistResponse\x12=\n" +
	"\rdocument_data\x18\x01 \x01(\v2\x16.analysis.DocumentDataH\x00R\fdocumentData\x12'\n" +
	"\x05score\x18\x02 \x01(\v2\x0f.analysis.ScoreH\x00R\x05scoreB\n" +
	"\n" +
	"\bresponse\"3\n" +
	"\x05Score\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x01R\x05score\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"\x9d\x01\n" +
	"\fDocumentData\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x1d\n" +
	"\n" +
	"page_count\x18\x03 \x01(\x05R\tpageCount\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x12$\n" +
	"\x05pages\x18\x05 \x03(\v2\x0e.analysis.PageR\x05pages\"8\n" +
	"\x04Page\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent2a\n" +
	"\x11SpecialistService\x12L\n" +
	"\rAnalyzeStream\x12\x1b.analysis.SpecialistRequest\x1a\x1c.analysis.SpecialistResponse(\x01B\x06Z\x04./pbb\x06proto3"

var (
	file_proto_specialist_specialist_service_proto_rawDescOnce sync.Once
	file_proto_specialist_specialist_service_proto_rawDescData []byte
)

func file_proto_specialist_specialist_service_proto_rawDescGZIP() []byte {
	file_proto_specialist_specialist_service_proto_rawDescOnce.Do(func() {
		file_proto_specialist_specialist_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_specialist_specialist_service_proto_rawDesc), len(file_proto_specialist_specialist_service_proto_rawDesc)))
	})
	return file_proto_specialist_specialist_service_proto_rawDescData
}

var file_proto_specialist_specialist_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_specialist_specialist_service_proto_goTypes = []any{
	(*SpecialistRequest)(nil),  // 0: analysis.SpecialistRequest
	(*Metadata)(nil),           // 1: analysis.Metadata
	(*SpecialistResponse)(nil), // 2: analysis.SpecialistResponse
	(*Score)(nil),              // 3: analysis.Score
	(*DocumentData)(nil),       // 4: analysis.DocumentData
	(*Page)(nil),               // 5: analysis.Page
}
var file_proto_specialist_specialist_service_proto_depIdxs = []int32{
	1, // 0: analysis.SpecialistRequest.metadata:type_name -> analysis.Metadata
	4, // 1: analysis.SpecialistResponse.document_data:type_name -> analysis.DocumentData
	3, // 2: analysis.SpecialistResponse.score:type_name -> analysis.Score
	5, // 3: analysis.DocumentData.pages:type_name -> analysis.Page
	0, // 4: analysis.SpecialistService.AnalyzeStream:input_type -> analysis.SpecialistRequest
	2, // 5: analysis.SpecialistService.AnalyzeStream:output_type -> analysis.SpecialistResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_specialist_specialist_service_proto_init() }
func file_proto_specialist_specialist_service_proto_init() {
	if File_proto_specialist_specialist_service_proto != nil {
		return
	}
	file_proto_specialist_specialist_service_proto_msgTypes[0].OneofWrappers = []any{
		(*SpecialistRequest_Metadata)(nil),
		(*SpecialistRequest_Chunk)(nil),
	}
	file_proto_specialist_specialist_service_proto_msgTypes[2].OneofWrappers = []any{
		(*SpecialistResponse_DocumentData)(nil),
		(*SpecialistResponse_Score)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_specialist_specialist_service_proto_rawDesc), len(file_proto_specialist_specialist_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_specialist_specialist_service_proto_goTypes,
		DependencyIndexes: file_proto_specialist_specialist_service_proto_depIdxs,
		MessageInfos:      file_proto_specialist_specialist_service_proto_msgTypes,
	}.Build()
	File_proto_specialist_specialist_service_proto = out.File
	file_proto_specialist_specialist_service_proto_goTypes = nil
	file_proto_specialist_specialist_service_proto_depIdxs = nil
}
