// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.31.1
// source: proto/specialist/specialist_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SpecialistService_AnalyzeStream_FullMethodName = "/analysis.SpecialistService/AnalyzeStream"
)

// SpecialistServiceClient is the client API for SpecialistService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SpecialistServiceClient interface {
	AnalyzeStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SpecialistRequest, SpecialistResponse], error)
}

type specialistServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSpecialistServiceClient(cc grpc.ClientConnInterface) SpecialistServiceClient {
	return &specialistServiceClient{cc}
}

func (c *specialistServiceClient) AnalyzeStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SpecialistRequest, SpecialistResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SpecialistService_ServiceDesc.Streams[0], SpecialistService_AnalyzeStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SpecialistRequest, SpecialistResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SpecialistService_AnalyzeStreamClient = grpc.ClientStreamingClient[SpecialistRequest, SpecialistResponse]

// SpecialistServiceServer is the server API for SpecialistService service.
// All implementations must embed UnimplementedSpecialistServiceServer
// for forward compatibility.
type SpecialistServiceServer interface {
	AnalyzeStream(grpc.ClientStreamingServer[SpecialistRequest, SpecialistResponse]) error
	mustEmbedUnimplementedSpecialistServiceServer()
}

// UnimplementedSpecialistServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSpecialistServiceServer struct{}

func (UnimplementedSpecialistServiceServer) AnalyzeStream(grpc.ClientStreamingServer[SpecialistRequest, SpecialistResponse]) error {
	return status.Error(codes.Unimplemented, "method AnalyzeStream not implemented")
}
func (UnimplementedSpecialistServiceServer) mustEmbedUnimplementedSpecialistServiceServer() {}
func (UnimplementedSpecialistServiceServer) testEmbeddedByValue()                           {}

// UnsafeSpecialistServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpecialistServiceServer will
// result in compilation errors.
type UnsafeSpecialistServiceServer interface {
	mustEmbedUnimplementedSpecialistServiceServer()
}

func RegisterSpecialistServiceServer(s grpc.ServiceRegistrar, srv SpecialistServiceServer) {
	// If the following call panics, it indicates UnimplementedSpecialistServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SpecialistService_ServiceDesc, srv)
}

func _SpecialistService_AnalyzeStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SpecialistServiceServer).AnalyzeStream(&grpc.GenericServerStream[SpecialistRequest, SpecialistResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SpecialistService_AnalyzeStreamServer = grpc.ClientStreamingServer[SpecialistRequest, SpecialistResponse]

// SpecialistService_ServiceDesc is the grpc.ServiceDesc for SpecialistService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpecialistService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analysis.SpecialistService",
	HandlerType: (*SpecialistServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AnalyzeStream",
			Handler:       _SpecialistService_AnalyzeStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/specialist/specialist_service.proto",
}
