# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto.specialist import specialist_service_pb2 as proto_dot_specialist_dot_specialist__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/specialist/specialist_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SpecialistServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeStream = channel.stream_unary(
                '/analysis.SpecialistService/AnalyzeStream',
                request_serializer=proto_dot_specialist_dot_specialist__service__pb2.SpecialistRequest.SerializeToString,
                response_deserializer=proto_dot_specialist_dot_specialist__service__pb2.SpecialistResponse.FromString,
                _registered_method=True)


class SpecialistServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AnalyzeStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpecialistServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeStream': grpc.stream_unary_rpc_method_handler(
                    servicer.AnalyzeStream,
                    request_deserializer=proto_dot_specialist_dot_specialist__service__pb2.SpecialistRequest.FromString,
                    response_serializer=proto_dot_specialist_dot_specialist__service__pb2.SpecialistResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'analysis.SpecialistService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('analysis.SpecialistService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SpecialistService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzeStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/analysis.SpecialistService/AnalyzeStream',
            proto_dot_specialist_dot_specialist__service__pb2.SpecialistRequest.SerializeToString,
            proto_dot_specialist_dot_specialist__service__pb2.SpecialistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
