// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: proto/monitoring/monitoring.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_monitoring_monitoring_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitoring_monitoring_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_monitoring_monitoring_proto_rawDescGZIP(), []int{0}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type NodeStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// --- Identification ---
	NodeId    string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`       // ex: "scanner-01" ou "specialist-toxicity-01"
	NodeType  string `protobuf:"bytes,2,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"` // "SCANNER", "MASTER", "SPECIALIST"
	Pid       int64  `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	PidStatus string `protobuf:"bytes,4,opt,name=pid_status,json=pidStatus,proto3" json:"pid_status,omitempty"` // IMPORTANT: "running", "sleep", "idle", etc.
	// --- System resources ---
	CpuPercent    float64 `protobuf:"fixed64,5,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	RamBytes      uint64  `protobuf:"varint,6,opt,name=ram_bytes,json=ramBytes,proto3" json:"ram_bytes,omitempty"`
	NumGoroutines uint32  `protobuf:"varint,7,opt,name=num_goroutines,json=numGoroutines,proto3" json:"num_goroutines,omitempty"`
	// --- Pipeline metric / Backpressure ---
	ItemsProcessed uint64 `protobuf:"varint,8,opt,name=items_processed,json=itemsProcessed,proto3" json:"items_processed,omitempty"`
	CurrentLoad    uint32 `protobuf:"varint,9,opt,name=current_load,json=currentLoad,proto3" json:"current_load,omitempty"`  // 0 or 1 for a specialist)
	QueueSize      uint32 `protobuf:"varint,10,opt,name=queue_size,json=queueSize,proto3" json:"queue_size,omitempty"`       // Waiting inside internal node
	MaxCapacity    uint32 `protobuf:"varint,11,opt,name=max_capacity,json=maxCapacity,proto3" json:"max_capacity,omitempty"` // Max channel capacity
	// --- Contexte Métier ---
	CurrentItemName string `protobuf:"bytes,12,opt,name=current_item_name,json=currentItemName,proto3" json:"current_item_name,omitempty"` // Name/UUID of the file being processed
	UptimeSeconds   uint64 `protobuf:"varint,13,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NodeStatus) Reset() {
	*x = NodeStatus{}
	mi := &file_proto_monitoring_monitoring_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatus) ProtoMessage() {}

func (x *NodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitoring_monitoring_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatus.ProtoReflect.Descriptor instead.
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return file_proto_monitoring_monitoring_proto_rawDescGZIP(), []int{1}
}

func (x *NodeStatus) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeStatus) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *NodeStatus) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *NodeStatus) GetPidStatus() string {
	if x != nil {
		return x.PidStatus
	}
	return ""
}

func (x *NodeStatus) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *NodeStatus) GetRamBytes() uint64 {
	if x != nil {
		return x.RamBytes
	}
	return 0
}

func (x *NodeStatus) GetNumGoroutines() uint32 {
	if x != nil {
		return x.NumGoroutines
	}
	return 0
}

func (x *NodeStatus) GetItemsProcessed() uint64 {
	if x != nil {
		return x.ItemsProcessed
	}
	return 0
}

func (x *NodeStatus) GetCurrentLoad() uint32 {
	if x != nil {
		return x.CurrentLoad
	}
	return 0
}

func (x *NodeStatus) GetQueueSize() uint32 {
	if x != nil {
		return x.QueueSize
	}
	return 0
}

func (x *NodeStatus) GetMaxCapacity() uint32 {
	if x != nil {
		return x.MaxCapacity
	}
	return 0
}

func (x *NodeStatus) GetCurrentItemName() string {
	if x != nil {
		return x.CurrentItemName
	}
	return ""
}

func (x *NodeStatus) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

var File_proto_monitoring_monitoring_proto protoreflect.FileDescriptor

const file_proto_monitoring_monitoring_proto_rawDesc = "" +
	"\n" +
	"!proto/monitoring/monitoring.proto\x12\banalysis\x1a\x1bgoogle/protobuf/empty.proto\"\x15\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\xb9\x03\n" +
	"\n" +
	"NodeStatus\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tnode_type\x18\x02 \x01(\tR\bnodeType\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\x03R\x03pid\x12\x1d\n" +
	"\n" +
	"pid_status\x18\x04 \x01(\tR\tpidStatus\x12\x1f\n" +
	"\vcpu_percent\x18\x05 \x01(\x01R\n" +
	"cpuPercent\x12\x1b\n" +
	"\tram_bytes\x18\x06 \x01(\x04R\bramBytes\x12%\n" +
	"\x0enum_goroutines\x18\a \x01(\rR\rnumGoroutines\x12'\n" +
	"\x0fitems_processed\x18\b \x01(\x04R\x0eitemsProcessed\x12!\n" +
	"\fcurrent_load\x18\t \x01(\rR\vcurrentLoad\x12\x1d\n" +
	"\n" +
	"queue_size\x18\n" +
	" \x01(\rR\tqueueSize\x12!\n" +
	"\fmax_capacity\x18\v \x01(\rR\vmaxCapacity\x12*\n" +
	"\x11current_item_name\x18\f \x01(\tR\x0fcurrentItemName\x12%\n" +
	"\x0euptime_seconds\x18\r \x01(\x04R\ruptimeSeconds2Q\n" +
	"\x11MonitoringService\x12<\n" +
	"\fReportStatus\x12\x14.analysis.NodeStatus\x1a\x16.google.protobuf.EmptyB\x06Z\x04./pbb\x06proto3"

var (
	file_proto_monitoring_monitoring_proto_rawDescOnce sync.Once
	file_proto_monitoring_monitoring_proto_rawDescData []byte
)

func file_proto_monitoring_monitoring_proto_rawDescGZIP() []byte {
	file_proto_monitoring_monitoring_proto_rawDescOnce.Do(func() {
		file_proto_monitoring_monitoring_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_monitoring_monitoring_proto_rawDesc), len(file_proto_monitoring_monitoring_proto_rawDesc)))
	})
	return file_proto_monitoring_monitoring_proto_rawDescData
}

var file_proto_monitoring_monitoring_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_monitoring_monitoring_proto_goTypes = []any{
	(*Ack)(nil),           // 0: analysis.Ack
	(*NodeStatus)(nil),    // 1: analysis.NodeStatus
	(*emptypb.Empty)(nil), // 2: google.protobuf.Empty
}
var file_proto_monitoring_monitoring_proto_depIdxs = []int32{
	1, // 0: analysis.MonitoringService.ReportStatus:input_type -> analysis.NodeStatus
	2, // 1: analysis.MonitoringService.ReportStatus:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_monitoring_monitoring_proto_init() }
func file_proto_monitoring_monitoring_proto_init() {
	if File_proto_monitoring_monitoring_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_monitoring_monitoring_proto_rawDesc), len(file_proto_monitoring_monitoring_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_monitoring_monitoring_proto_goTypes,
		DependencyIndexes: file_proto_monitoring_monitoring_proto_depIdxs,
		MessageInfos:      file_proto_monitoring_monitoring_proto_msgTypes,
	}.Build()
	File_proto_monitoring_monitoring_proto = out.File
	file_proto_monitoring_monitoring_proto_goTypes = nil
	file_proto_monitoring_monitoring_proto_depIdxs = nil
}
