# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/monitoring/monitoring.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/monitoring/monitoring.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!proto/monitoring/monitoring.proto\x12\x08\x61nalysis\x1a\x1bgoogle/protobuf/empty.proto\"\x11\n\x03\x41\x63k\x12\n\n\x02ok\x18\x01 \x01(\x08\"\x9d\x02\n\nNodeStatus\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x11\n\tnode_type\x18\x02 \x01(\t\x12\x0b\n\x03pid\x18\x03 \x01(\x03\x12\x12\n\npid_status\x18\x04 \x01(\t\x12\x13\n\x0b\x63pu_percent\x18\x05 \x01(\x01\x12\x11\n\tram_bytes\x18\x06 \x01(\x04\x12\x16\n\x0enum_goroutines\x18\x07 \x01(\r\x12\x17\n\x0fitems_processed\x18\x08 \x01(\x04\x12\x14\n\x0c\x63urrent_load\x18\t \x01(\r\x12\x12\n\nqueue_size\x18\n \x01(\r\x12\x14\n\x0cmax_capacity\x18\x0b \x01(\r\x12\x19\n\x11\x63urrent_item_name\x18\x0c \x01(\t\x12\x16\n\x0euptime_seconds\x18\r \x01(\x04\x32Q\n\x11MonitoringService\x12<\n\x0cReportStatus\x12\x14.analysis.NodeStatus\x1a\x16.google.protobuf.EmptyB\x06Z\x04./pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.monitoring.monitoring_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004./pb'
  _globals['_ACK']._serialized_start=76
  _globals['_ACK']._serialized_end=93
  _globals['_NODESTATUS']._serialized_start=96
  _globals['_NODESTATUS']._serialized_end=381
  _globals['_MONITORINGSERVICE']._serialized_start=383
  _globals['_MONITORINGSERVICE']._serialized_end=464
# @@protoc_insertion_point(module_scope)
