// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: proto/analyzer/file_scanner_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_proto_analyzer_file_scanner_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analyzer_file_scanner_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_proto_analyzer_file_scanner_service_proto_rawDescGZIP(), []int{0}
}

func (x *ScanRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Started       bool                   `protobuf:"varint,1,opt,name=started,proto3" json:"started,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_proto_analyzer_file_scanner_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analyzer_file_scanner_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_proto_analyzer_file_scanner_service_proto_rawDescGZIP(), []int{1}
}

func (x *ScanResponse) GetStarted() bool {
	if x != nil {
		return x.Started
	}
	return false
}

func (x *ScanResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_analyzer_file_scanner_service_proto protoreflect.FileDescriptor

const file_proto_analyzer_file_scanner_service_proto_rawDesc = "" +
	"\n" +
	")proto/analyzer/file_scanner_service.proto\x12\banalyzer\"!\n" +
	"\vScanRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"B\n" +
	"\fScanResponse\x12\x18\n" +
	"\astarted\x18\x01 \x01(\bR\astarted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2Q\n" +
	"\x11ScannerController\x12<\n" +
	"\vTriggerScan\x12\x15.analyzer.ScanRequest\x1a\x16.analyzer.ScanResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_proto_analyzer_file_scanner_service_proto_rawDescOnce sync.Once
	file_proto_analyzer_file_scanner_service_proto_rawDescData []byte
)

func file_proto_analyzer_file_scanner_service_proto_rawDescGZIP() []byte {
	file_proto_analyzer_file_scanner_service_proto_rawDescOnce.Do(func() {
		file_proto_analyzer_file_scanner_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_analyzer_file_scanner_service_proto_rawDesc), len(file_proto_analyzer_file_scanner_service_proto_rawDesc)))
	})
	return file_proto_analyzer_file_scanner_service_proto_rawDescData
}

var file_proto_analyzer_file_scanner_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_analyzer_file_scanner_service_proto_goTypes = []any{
	(*ScanRequest)(nil),  // 0: analyzer.ScanRequest
	(*ScanResponse)(nil), // 1: analyzer.ScanResponse
}
var file_proto_analyzer_file_scanner_service_proto_depIdxs = []int32{
	0, // 0: analyzer.ScannerController.TriggerScan:input_type -> analyzer.ScanRequest
	1, // 1: analyzer.ScannerController.TriggerScan:output_type -> analyzer.ScanResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_analyzer_file_scanner_service_proto_init() }
func file_proto_analyzer_file_scanner_service_proto_init() {
	if File_proto_analyzer_file_scanner_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_analyzer_file_scanner_service_proto_rawDesc), len(file_proto_analyzer_file_scanner_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_analyzer_file_scanner_service_proto_goTypes,
		DependencyIndexes: file_proto_analyzer_file_scanner_service_proto_depIdxs,
		MessageInfos:      file_proto_analyzer_file_scanner_service_proto_msgTypes,
	}.Build()
	File_proto_analyzer_file_scanner_service_proto = out.File
	file_proto_analyzer_file_scanner_service_proto_goTypes = nil
	file_proto_analyzer_file_scanner_service_proto_depIdxs = nil
}
