// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.31.1
// source: proto/analyzer/file_scanner_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScannerController_TriggerScan_FullMethodName = "/analyzer.ScannerController/TriggerScan"
)

// ScannerControllerClient is the client API for ScannerController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScannerControllerClient interface {
	TriggerScan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error)
}

type scannerControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewScannerControllerClient(cc grpc.ClientConnInterface) ScannerControllerClient {
	return &scannerControllerClient{cc}
}

func (c *scannerControllerClient) TriggerScan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScanResponse)
	err := c.cc.Invoke(ctx, ScannerController_TriggerScan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScannerControllerServer is the server API for ScannerController service.
// All implementations must embed UnimplementedScannerControllerServer
// for forward compatibility.
type ScannerControllerServer interface {
	TriggerScan(context.Context, *ScanRequest) (*ScanResponse, error)
	mustEmbedUnimplementedScannerControllerServer()
}

// UnimplementedScannerControllerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScannerControllerServer struct{}

func (UnimplementedScannerControllerServer) TriggerScan(context.Context, *ScanRequest) (*ScanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerScan not implemented")
}
func (UnimplementedScannerControllerServer) mustEmbedUnimplementedScannerControllerServer() {}
func (UnimplementedScannerControllerServer) testEmbeddedByValue()                           {}

// UnsafeScannerControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScannerControllerServer will
// result in compilation errors.
type UnsafeScannerControllerServer interface {
	mustEmbedUnimplementedScannerControllerServer()
}

func RegisterScannerControllerServer(s grpc.ServiceRegistrar, srv ScannerControllerServer) {
	// If the following call panics, it indicates UnimplementedScannerControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScannerController_ServiceDesc, srv)
}

func _ScannerController_TriggerScan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScannerControllerServer).TriggerScan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScannerController_TriggerScan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScannerControllerServer).TriggerScan(ctx, req.(*ScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScannerController_ServiceDesc is the grpc.ServiceDesc for ScannerController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScannerController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analyzer.ScannerController",
	HandlerType: (*ScannerControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TriggerScan",
			Handler:    _ScannerController_TriggerScan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/analyzer/file_scanner_service.proto",
}
