# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto.analyzer import file_downloader_service_pb2 as proto_dot_analyzer_dot_file__downloader__service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/analyzer/file_downloader_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FileDownloaderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Download = channel.stream_stream(
                '/analyzer.FileDownloaderService/Download',
                request_serializer=proto_dot_analyzer_dot_file__downloader__service__pb2.FileDownloaderRequest.SerializeToString,
                response_deserializer=proto_dot_analyzer_dot_file__downloader__service__pb2.FileDownloaderResponse.FromString,
                _registered_method=True)


class FileDownloaderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Download(self, request_iterator, context):
        """Bidirectional stream for high-performance multiplexed transfers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileDownloaderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Download': grpc.stream_stream_rpc_method_handler(
                    servicer.Download,
                    request_deserializer=proto_dot_analyzer_dot_file__downloader__service__pb2.FileDownloaderRequest.FromString,
                    response_serializer=proto_dot_analyzer_dot_file__downloader__service__pb2.FileDownloaderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'analyzer.FileDownloaderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('analyzer.FileDownloaderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileDownloaderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Download(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/analyzer.FileDownloaderService/Download',
            proto_dot_analyzer_dot_file__downloader__service__pb2.FileDownloaderRequest.SerializeToString,
            proto_dot_analyzer_dot_file__downloader__service__pb2.FileDownloaderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
