// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: proto/analyzer/file_downloader_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_INVALID_FILE_PATH ErrorCode = 0
	ErrorCode_NOT_FOUND         ErrorCode = 1
	ErrorCode_ACCESS_DENIED     ErrorCode = 2
	ErrorCode_NOT_FILE          ErrorCode = 3
	ErrorCode_FILE_TOO_LARGE    ErrorCode = 4
	ErrorCode_CHECKSUM_MISMATCH ErrorCode = 5
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "INVALID_FILE_PATH",
		1: "NOT_FOUND",
		2: "ACCESS_DENIED",
		3: "NOT_FILE",
		4: "FILE_TOO_LARGE",
		5: "CHECKSUM_MISMATCH",
	}
	ErrorCode_value = map[string]int32{
		"INVALID_FILE_PATH": 0,
		"NOT_FOUND":         1,
		"ACCESS_DENIED":     2,
		"NOT_FILE":          3,
		"FILE_TOO_LARGE":    4,
		"CHECKSUM_MISMATCH": 5,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_analyzer_file_downloader_service_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_proto_analyzer_file_downloader_service_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_analyzer_file_downloader_service_proto_rawDescGZIP(), []int{0}
}

type FileDownloaderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"` // Better than path for security (obfuscation)
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`                   // The actual path on the scanner's disk
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDownloaderRequest) Reset() {
	*x = FileDownloaderRequest{}
	mi := &file_proto_analyzer_file_downloader_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDownloaderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDownloaderRequest) ProtoMessage() {}

func (x *FileDownloaderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analyzer_file_downloader_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDownloaderRequest.ProtoReflect.Descriptor instead.
func (*FileDownloaderRequest) Descriptor() ([]byte, []int) {
	return file_proto_analyzer_file_downloader_service_proto_rawDescGZIP(), []int{0}
}

func (x *FileDownloaderRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FileDownloaderRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type FileDownloaderResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Control:
	//
	//	*FileDownloaderResponse_Metadata
	//	*FileDownloaderResponse_Chunk
	//	*FileDownloaderResponse_Signature
	//	*FileDownloaderResponse_Error
	Control       isFileDownloaderResponse_Control `protobuf_oneof:"control"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDownloaderResponse) Reset() {
	*x = FileDownloaderResponse{}
	mi := &file_proto_analyzer_file_downloader_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDownloaderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDownloaderResponse) ProtoMessage() {}

func (x *FileDownloaderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analyzer_file_downloader_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDownloaderResponse.ProtoReflect.Descriptor instead.
func (*FileDownloaderResponse) Descriptor() ([]byte, []int) {
	return file_proto_analyzer_file_downloader_service_proto_rawDescGZIP(), []int{1}
}

func (x *FileDownloaderResponse) GetControl() isFileDownloaderResponse_Control {
	if x != nil {
		return x.Control
	}
	return nil
}

func (x *FileDownloaderResponse) GetMetadata() *FileMetadata {
	if x != nil {
		if x, ok := x.Control.(*FileDownloaderResponse_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *FileDownloaderResponse) GetChunk() *FileChunk {
	if x != nil {
		if x, ok := x.Control.(*FileDownloaderResponse_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *FileDownloaderResponse) GetSignature() *FileSignature {
	if x != nil {
		if x, ok := x.Control.(*FileDownloaderResponse_Signature); ok {
			return x.Signature
		}
	}
	return nil
}

func (x *FileDownloaderResponse) GetError() *FileError {
	if x != nil {
		if x, ok := x.Control.(*FileDownloaderResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isFileDownloaderResponse_Control interface {
	isFileDownloaderResponse_Control()
}

type FileDownloaderResponse_Metadata struct {
	Metadata *FileMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"` // Sent once at the start of a file
}

type FileDownloaderResponse_Chunk struct {
	Chunk *FileChunk `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"` // Sent multiple times
}

type FileDownloaderResponse_Signature struct {
	Signature *FileSignature `protobuf:"bytes,3,opt,name=signature,proto3,oneof"` // Sent once
}

type FileDownloaderResponse_Error struct {
	Error *FileError `protobuf:"bytes,4,opt,name=error,proto3,oneof"` // In case the scanner detects an issue
}

func (*FileDownloaderResponse_Metadata) isFileDownloaderResponse_Control() {}

func (*FileDownloaderResponse_Chunk) isFileDownloaderResponse_Control() {}

func (*FileDownloaderResponse_Signature) isFileDownloaderResponse_Control() {}

func (*FileDownloaderResponse_Error) isFileDownloaderResponse_Control() {}

type FileMetadata struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RawMimeType       string                 `protobuf:"bytes,1,opt,name=raw_mime_type,json=rawMimeType,proto3" json:"raw_mime_type,omitempty"` // To check against the expected type
	EffectiveMimeType string                 `protobuf:"bytes,2,opt,name=effective_mime_type,json=effectiveMimeType,proto3" json:"effective_mime_type,omitempty"`
	Size              uint64                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"` // To prevent "Zip Bombs" or overflow
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	mi := &file_proto_analyzer_file_downloader_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analyzer_file_downloader_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadata.ProtoReflect.Descriptor instead.
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return file_proto_analyzer_file_downloader_service_proto_rawDescGZIP(), []int{2}
}

func (x *FileMetadata) GetRawMimeType() string {
	if x != nil {
		return x.RawMimeType
	}
	return ""
}

func (x *FileMetadata) GetEffectiveMimeType() string {
	if x != nil {
		return x.EffectiveMimeType
	}
	return ""
}

func (x *FileMetadata) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_proto_analyzer_file_downloader_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analyzer_file_downloader_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_proto_analyzer_file_downloader_service_proto_rawDescGZIP(), []int{3}
}

func (x *FileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type FileSignature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sha256        string                 `protobuf:"bytes,1,opt,name=sha256,proto3" json:"sha256,omitempty"` // To be verified by the Master at the end
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileSignature) Reset() {
	*x = FileSignature{}
	mi := &file_proto_analyzer_file_downloader_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileSignature) ProtoMessage() {}

func (x *FileSignature) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analyzer_file_downloader_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileSignature.ProtoReflect.Descriptor instead.
func (*FileSignature) Descriptor() ([]byte, []int) {
	return file_proto_analyzer_file_downloader_service_proto_rawDescGZIP(), []int{4}
}

func (x *FileSignature) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type FileError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code          ErrorCode              `protobuf:"varint,2,opt,name=code,proto3,enum=analyzer.ErrorCode" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileError) Reset() {
	*x = FileError{}
	mi := &file_proto_analyzer_file_downloader_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileError) ProtoMessage() {}

func (x *FileError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analyzer_file_downloader_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileError.ProtoReflect.Descriptor instead.
func (*FileError) Descriptor() ([]byte, []int) {
	return file_proto_analyzer_file_downloader_service_proto_rawDescGZIP(), []int{5}
}

func (x *FileError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FileError) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_INVALID_FILE_PATH
}

var File_proto_analyzer_file_downloader_service_proto protoreflect.FileDescriptor

const file_proto_analyzer_file_downloader_service_proto_rawDesc = "" +
	"\n" +
	",proto/analyzer/file_downloader_service.proto\x12\banalyzer\"D\n" +
	"\x15FileDownloaderRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\xec\x01\n" +
	"\x16FileDownloaderResponse\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x16.analyzer.FileMetadataH\x00R\bmetadata\x12+\n" +
	"\x05chunk\x18\x02 \x01(\v2\x13.analyzer.FileChunkH\x00R\x05chunk\x127\n" +
	"\tsignature\x18\x03 \x01(\v2\x17.analyzer.FileSignatureH\x00R\tsignature\x12+\n" +
	"\x05error\x18\x04 \x01(\v2\x13.analyzer.FileErrorH\x00R\x05errorB\t\n" +
	"\acontrol\"v\n" +
	"\fFileMetadata\x12\"\n" +
	"\rraw_mime_type\x18\x01 \x01(\tR\vrawMimeType\x12.\n" +
	"\x13effective_mime_type\x18\x02 \x01(\tR\x11effectiveMimeType\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\"\x1f\n" +
	"\tFileChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"'\n" +
	"\rFileSignature\x12\x16\n" +
	"\x06sha256\x18\x01 \x01(\tR\x06sha256\"N\n" +
	"\tFileError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12'\n" +
	"\x04code\x18\x02 \x01(\x0e2\x13.analyzer.ErrorCodeR\x04code*}\n" +
	"\tErrorCode\x12\x15\n" +
	"\x11INVALID_FILE_PATH\x10\x00\x12\r\n" +
	"\tNOT_FOUND\x10\x01\x12\x11\n" +
	"\rACCESS_DENIED\x10\x02\x12\f\n" +
	"\bNOT_FILE\x10\x03\x12\x12\n" +
	"\x0eFILE_TOO_LARGE\x10\x04\x12\x15\n" +
	"\x11CHECKSUM_MISMATCH\x10\x052j\n" +
	"\x15FileDownloaderService\x12Q\n" +
	"\bDownload\x12\x1f.analyzer.FileDownloaderRequest\x1a .analyzer.FileDownloaderResponse(\x010\x01B\x06Z\x04./pbb\x06proto3"

var (
	file_proto_analyzer_file_downloader_service_proto_rawDescOnce sync.Once
	file_proto_analyzer_file_downloader_service_proto_rawDescData []byte
)

func file_proto_analyzer_file_downloader_service_proto_rawDescGZIP() []byte {
	file_proto_analyzer_file_downloader_service_proto_rawDescOnce.Do(func() {
		file_proto_analyzer_file_downloader_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_analyzer_file_downloader_service_proto_rawDesc), len(file_proto_analyzer_file_downloader_service_proto_rawDesc)))
	})
	return file_proto_analyzer_file_downloader_service_proto_rawDescData
}

var file_proto_analyzer_file_downloader_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_analyzer_file_downloader_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_analyzer_file_downloader_service_proto_goTypes = []any{
	(ErrorCode)(0),                 // 0: analyzer.ErrorCode
	(*FileDownloaderRequest)(nil),  // 1: analyzer.FileDownloaderRequest
	(*FileDownloaderResponse)(nil), // 2: analyzer.FileDownloaderResponse
	(*FileMetadata)(nil),           // 3: analyzer.FileMetadata
	(*FileChunk)(nil),              // 4: analyzer.FileChunk
	(*FileSignature)(nil),          // 5: analyzer.FileSignature
	(*FileError)(nil),              // 6: analyzer.FileError
}
var file_proto_analyzer_file_downloader_service_proto_depIdxs = []int32{
	3, // 0: analyzer.FileDownloaderResponse.metadata:type_name -> analyzer.FileMetadata
	4, // 1: analyzer.FileDownloaderResponse.chunk:type_name -> analyzer.FileChunk
	5, // 2: analyzer.FileDownloaderResponse.signature:type_name -> analyzer.FileSignature
	6, // 3: analyzer.FileDownloaderResponse.error:type_name -> analyzer.FileError
	0, // 4: analyzer.FileError.code:type_name -> analyzer.ErrorCode
	1, // 5: analyzer.FileDownloaderService.Download:input_type -> analyzer.FileDownloaderRequest
	2, // 6: analyzer.FileDownloaderService.Download:output_type -> analyzer.FileDownloaderResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_analyzer_file_downloader_service_proto_init() }
func file_proto_analyzer_file_downloader_service_proto_init() {
	if File_proto_analyzer_file_downloader_service_proto != nil {
		return
	}
	file_proto_analyzer_file_downloader_service_proto_msgTypes[1].OneofWrappers = []any{
		(*FileDownloaderResponse_Metadata)(nil),
		(*FileDownloaderResponse_Chunk)(nil),
		(*FileDownloaderResponse_Signature)(nil),
		(*FileDownloaderResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_analyzer_file_downloader_service_proto_rawDesc), len(file_proto_analyzer_file_downloader_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_analyzer_file_downloader_service_proto_goTypes,
		DependencyIndexes: file_proto_analyzer_file_downloader_service_proto_depIdxs,
		EnumInfos:         file_proto_analyzer_file_downloader_service_proto_enumTypes,
		MessageInfos:      file_proto_analyzer_file_downloader_service_proto_msgTypes,
	}.Build()
	File_proto_analyzer_file_downloader_service_proto = out.File
	file_proto_analyzer_file_downloader_service_proto_goTypes = nil
	file_proto_analyzer_file_downloader_service_proto_depIdxs = nil
}
