// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: proto/analyzer/file_analyzer_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SourceType int32

const (
	SourceType_UNSPECIFIED SourceType = 0
	SourceType_LOCAL_FIXED SourceType = 1 // Internal SSD/HDD
	SourceType_REMOVABLE   SourceType = 2 // USB / Carte SD
	SourceType_NETWORK     SourceType = 3 // NAS / SMB
)

// Enum value maps for SourceType.
var (
	SourceType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "LOCAL_FIXED",
		2: "REMOVABLE",
		3: "NETWORK",
	}
	SourceType_value = map[string]int32{
		"UNSPECIFIED": 0,
		"LOCAL_FIXED": 1,
		"REMOVABLE":   2,
		"NETWORK":     3,
	}
)

func (x SourceType) Enum() *SourceType {
	p := new(SourceType)
	*p = x
	return p
}

func (x SourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_analyzer_file_analyzer_service_proto_enumTypes[0].Descriptor()
}

func (SourceType) Type() protoreflect.EnumType {
	return &file_proto_analyzer_file_analyzer_service_proto_enumTypes[0]
}

func (x SourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SourceType.Descriptor instead.
func (SourceType) EnumDescriptor() ([]byte, []int) {
	return file_proto_analyzer_file_analyzer_service_proto_rawDescGZIP(), []int{0}
}

type FileAnalyzerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Complete path (ex: E:\Photos\holidays.jpg)
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// ex: Disk UUID
	DriveId string `protobuf:"bytes,2,opt,name=drive_id,json=driveId,proto3" json:"drive_id,omitempty"`
	// System metadata (from syscalls)
	Size uint64 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	// Bit mask Windows
	Attributes uint32 `protobuf:"varint,4,opt,name=attributes,proto3" json:"attributes,omitempty"`
	// Local intelligence (Sniffing)
	MimeType string `protobuf:"bytes,5,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	// First 512 bytes
	MagicBytes []byte `protobuf:"bytes,6,opt,name=magic_bytes,json=magicBytes,proto3" json:"magic_bytes,omitempty"`
	// Context
	ScannedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=scanned_at,json=scannedAt,proto3" json:"scanned_at,omitempty"`
	SourceType    SourceType             `protobuf:"varint,8,opt,name=source_type,json=sourceType,proto3,enum=analyzer.SourceType" json:"source_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileAnalyzerRequest) Reset() {
	*x = FileAnalyzerRequest{}
	mi := &file_proto_analyzer_file_analyzer_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileAnalyzerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileAnalyzerRequest) ProtoMessage() {}

func (x *FileAnalyzerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analyzer_file_analyzer_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileAnalyzerRequest.ProtoReflect.Descriptor instead.
func (*FileAnalyzerRequest) Descriptor() ([]byte, []int) {
	return file_proto_analyzer_file_analyzer_service_proto_rawDescGZIP(), []int{0}
}

func (x *FileAnalyzerRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileAnalyzerRequest) GetDriveId() string {
	if x != nil {
		return x.DriveId
	}
	return ""
}

func (x *FileAnalyzerRequest) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileAnalyzerRequest) GetAttributes() uint32 {
	if x != nil {
		return x.Attributes
	}
	return 0
}

func (x *FileAnalyzerRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *FileAnalyzerRequest) GetMagicBytes() []byte {
	if x != nil {
		return x.MagicBytes
	}
	return nil
}

func (x *FileAnalyzerRequest) GetScannedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScannedAt
	}
	return nil
}

func (x *FileAnalyzerRequest) GetSourceType() SourceType {
	if x != nil {
		return x.SourceType
	}
	return SourceType_UNSPECIFIED
}

type FileAnalyzerResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FilesReceived  uint64                 `protobuf:"varint,1,opt,name=files_received,json=filesReceived,proto3" json:"files_received,omitempty"`
	BytesProcessed uint64                 `protobuf:"varint,2,opt,name=bytes_processed,json=bytesProcessed,proto3" json:"bytes_processed,omitempty"`
	EndedAt        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FileAnalyzerResponse) Reset() {
	*x = FileAnalyzerResponse{}
	mi := &file_proto_analyzer_file_analyzer_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileAnalyzerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileAnalyzerResponse) ProtoMessage() {}

func (x *FileAnalyzerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analyzer_file_analyzer_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileAnalyzerResponse.ProtoReflect.Descriptor instead.
func (*FileAnalyzerResponse) Descriptor() ([]byte, []int) {
	return file_proto_analyzer_file_analyzer_service_proto_rawDescGZIP(), []int{1}
}

func (x *FileAnalyzerResponse) GetFilesReceived() uint64 {
	if x != nil {
		return x.FilesReceived
	}
	return 0
}

func (x *FileAnalyzerResponse) GetBytesProcessed() uint64 {
	if x != nil {
		return x.BytesProcessed
	}
	return 0
}

func (x *FileAnalyzerResponse) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

var File_proto_analyzer_file_analyzer_service_proto protoreflect.FileDescriptor

const file_proto_analyzer_file_analyzer_service_proto_rawDesc = "" +
	"\n" +
	"*proto/analyzer/file_analyzer_service.proto\x12\banalyzer\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa8\x02\n" +
	"\x13FileAnalyzerRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x19\n" +
	"\bdrive_id\x18\x02 \x01(\tR\adriveId\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\x12\x1e\n" +
	"\n" +
	"attributes\x18\x04 \x01(\rR\n" +
	"attributes\x12\x1b\n" +
	"\tmime_type\x18\x05 \x01(\tR\bmimeType\x12\x1f\n" +
	"\vmagic_bytes\x18\x06 \x01(\fR\n" +
	"magicBytes\x129\n" +
	"\n" +
	"scanned_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tscannedAt\x125\n" +
	"\vsource_type\x18\b \x01(\x0e2\x14.analyzer.SourceTypeR\n" +
	"sourceType\"\x9d\x01\n" +
	"\x14FileAnalyzerResponse\x12%\n" +
	"\x0efiles_received\x18\x01 \x01(\x04R\rfilesReceived\x12'\n" +
	"\x0fbytes_processed\x18\x02 \x01(\x04R\x0ebytesProcessed\x125\n" +
	"\bended_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt*J\n" +
	"\n" +
	"SourceType\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vLOCAL_FIXED\x10\x01\x12\r\n" +
	"\tREMOVABLE\x10\x02\x12\v\n" +
	"\aNETWORK\x10\x032a\n" +
	"\x13FileAnalyzerService\x12J\n" +
	"\aAnalyze\x12\x1d.analyzer.FileAnalyzerRequest\x1a\x1e.analyzer.FileAnalyzerResponse(\x01B\x06Z\x04./pbb\x06proto3"

var (
	file_proto_analyzer_file_analyzer_service_proto_rawDescOnce sync.Once
	file_proto_analyzer_file_analyzer_service_proto_rawDescData []byte
)

func file_proto_analyzer_file_analyzer_service_proto_rawDescGZIP() []byte {
	file_proto_analyzer_file_analyzer_service_proto_rawDescOnce.Do(func() {
		file_proto_analyzer_file_analyzer_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_analyzer_file_analyzer_service_proto_rawDesc), len(file_proto_analyzer_file_analyzer_service_proto_rawDesc)))
	})
	return file_proto_analyzer_file_analyzer_service_proto_rawDescData
}

var file_proto_analyzer_file_analyzer_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_analyzer_file_analyzer_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_analyzer_file_analyzer_service_proto_goTypes = []any{
	(SourceType)(0),               // 0: analyzer.SourceType
	(*FileAnalyzerRequest)(nil),   // 1: analyzer.FileAnalyzerRequest
	(*FileAnalyzerResponse)(nil),  // 2: analyzer.FileAnalyzerResponse
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_proto_analyzer_file_analyzer_service_proto_depIdxs = []int32{
	3, // 0: analyzer.FileAnalyzerRequest.scanned_at:type_name -> google.protobuf.Timestamp
	0, // 1: analyzer.FileAnalyzerRequest.source_type:type_name -> analyzer.SourceType
	3, // 2: analyzer.FileAnalyzerResponse.ended_at:type_name -> google.protobuf.Timestamp
	1, // 3: analyzer.FileAnalyzerService.Analyze:input_type -> analyzer.FileAnalyzerRequest
	2, // 4: analyzer.FileAnalyzerService.Analyze:output_type -> analyzer.FileAnalyzerResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_analyzer_file_analyzer_service_proto_init() }
func file_proto_analyzer_file_analyzer_service_proto_init() {
	if File_proto_analyzer_file_analyzer_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_analyzer_file_analyzer_service_proto_rawDesc), len(file_proto_analyzer_file_analyzer_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_analyzer_file_analyzer_service_proto_goTypes,
		DependencyIndexes: file_proto_analyzer_file_analyzer_service_proto_depIdxs,
		EnumInfos:         file_proto_analyzer_file_analyzer_service_proto_enumTypes,
		MessageInfos:      file_proto_analyzer_file_analyzer_service_proto_msgTypes,
	}.Build()
	File_proto_analyzer_file_analyzer_service_proto = out.File
	file_proto_analyzer_file_analyzer_service_proto_goTypes = nil
	file_proto_analyzer_file_analyzer_service_proto_depIdxs = nil
}
