// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.31.1
// source: proto/analyzer/file_analyzer_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FileAnalyzerService_Analyze_FullMethodName = "/analyzer.FileAnalyzerService/Analyze"
)

// FileAnalyzerServiceClient is the client API for FileAnalyzerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileAnalyzerServiceClient interface {
	Analyze(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileAnalyzerRequest, FileAnalyzerResponse], error)
}

type fileAnalyzerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileAnalyzerServiceClient(cc grpc.ClientConnInterface) FileAnalyzerServiceClient {
	return &fileAnalyzerServiceClient{cc}
}

func (c *fileAnalyzerServiceClient) Analyze(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileAnalyzerRequest, FileAnalyzerResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FileAnalyzerService_ServiceDesc.Streams[0], FileAnalyzerService_Analyze_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileAnalyzerRequest, FileAnalyzerResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileAnalyzerService_AnalyzeClient = grpc.ClientStreamingClient[FileAnalyzerRequest, FileAnalyzerResponse]

// FileAnalyzerServiceServer is the server API for FileAnalyzerService service.
// All implementations must embed UnimplementedFileAnalyzerServiceServer
// for forward compatibility.
type FileAnalyzerServiceServer interface {
	Analyze(grpc.ClientStreamingServer[FileAnalyzerRequest, FileAnalyzerResponse]) error
	mustEmbedUnimplementedFileAnalyzerServiceServer()
}

// UnimplementedFileAnalyzerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileAnalyzerServiceServer struct{}

func (UnimplementedFileAnalyzerServiceServer) Analyze(grpc.ClientStreamingServer[FileAnalyzerRequest, FileAnalyzerResponse]) error {
	return status.Error(codes.Unimplemented, "method Analyze not implemented")
}
func (UnimplementedFileAnalyzerServiceServer) mustEmbedUnimplementedFileAnalyzerServiceServer() {}
func (UnimplementedFileAnalyzerServiceServer) testEmbeddedByValue()                             {}

// UnsafeFileAnalyzerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileAnalyzerServiceServer will
// result in compilation errors.
type UnsafeFileAnalyzerServiceServer interface {
	mustEmbedUnimplementedFileAnalyzerServiceServer()
}

func RegisterFileAnalyzerServiceServer(s grpc.ServiceRegistrar, srv FileAnalyzerServiceServer) {
	// If the following call panics, it indicates UnimplementedFileAnalyzerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileAnalyzerService_ServiceDesc, srv)
}

func _FileAnalyzerService_Analyze_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FileAnalyzerServiceServer).Analyze(&grpc.GenericServerStream[FileAnalyzerRequest, FileAnalyzerResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileAnalyzerService_AnalyzeServer = grpc.ClientStreamingServer[FileAnalyzerRequest, FileAnalyzerResponse]

// FileAnalyzerService_ServiceDesc is the grpc.ServiceDesc for FileAnalyzerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileAnalyzerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analyzer.FileAnalyzerService",
	HandlerType: (*FileAnalyzerServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Analyze",
			Handler:       _FileAnalyzerService_Analyze_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/analyzer/file_analyzer_service.proto",
}
