# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto.analyzer import file_analyzer_service_pb2 as proto_dot_analyzer_dot_file__analyzer__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/analyzer/file_analyzer_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FileAnalyzerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Analyze = channel.stream_unary(
                '/ingestion.FileAnalyzerService/Analyze',
                request_serializer=proto_dot_analyzer_dot_file__analyzer__service__pb2.FileAnalyzerRequest.SerializeToString,
                response_deserializer=proto_dot_analyzer_dot_file__analyzer__service__pb2.FileAnalyzerResponse.FromString,
                _registered_method=True)


class FileAnalyzerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Analyze(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileAnalyzerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Analyze': grpc.stream_unary_rpc_method_handler(
                    servicer.Analyze,
                    request_deserializer=proto_dot_analyzer_dot_file__analyzer__service__pb2.FileAnalyzerRequest.FromString,
                    response_serializer=proto_dot_analyzer_dot_file__analyzer__service__pb2.FileAnalyzerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ingestion.FileAnalyzerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ingestion.FileAnalyzerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileAnalyzerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Analyze(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/ingestion.FileAnalyzerService/Analyze',
            proto_dot_analyzer_dot_file__analyzer__service__pb2.FileAnalyzerRequest.SerializeToString,
            proto_dot_analyzer_dot_file__analyzer__service__pb2.FileAnalyzerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
