// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.31.1
// source: proto/analyzer/file_downloader_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FileDownloaderService_Download_FullMethodName = "/analyzer.FileDownloaderService/Download"
)

// FileDownloaderServiceClient is the client API for FileDownloaderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileDownloaderServiceClient interface {
	// Bidirectional stream for high-performance multiplexed transfers
	Download(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FileDownloaderRequest, FileDownloaderResponse], error)
}

type fileDownloaderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileDownloaderServiceClient(cc grpc.ClientConnInterface) FileDownloaderServiceClient {
	return &fileDownloaderServiceClient{cc}
}

func (c *fileDownloaderServiceClient) Download(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FileDownloaderRequest, FileDownloaderResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FileDownloaderService_ServiceDesc.Streams[0], FileDownloaderService_Download_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileDownloaderRequest, FileDownloaderResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileDownloaderService_DownloadClient = grpc.BidiStreamingClient[FileDownloaderRequest, FileDownloaderResponse]

// FileDownloaderServiceServer is the server API for FileDownloaderService service.
// All implementations must embed UnimplementedFileDownloaderServiceServer
// for forward compatibility.
type FileDownloaderServiceServer interface {
	// Bidirectional stream for high-performance multiplexed transfers
	Download(grpc.BidiStreamingServer[FileDownloaderRequest, FileDownloaderResponse]) error
	mustEmbedUnimplementedFileDownloaderServiceServer()
}

// UnimplementedFileDownloaderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileDownloaderServiceServer struct{}

func (UnimplementedFileDownloaderServiceServer) Download(grpc.BidiStreamingServer[FileDownloaderRequest, FileDownloaderResponse]) error {
	return status.Error(codes.Unimplemented, "method Download not implemented")
}
func (UnimplementedFileDownloaderServiceServer) mustEmbedUnimplementedFileDownloaderServiceServer() {}
func (UnimplementedFileDownloaderServiceServer) testEmbeddedByValue()                               {}

// UnsafeFileDownloaderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileDownloaderServiceServer will
// result in compilation errors.
type UnsafeFileDownloaderServiceServer interface {
	mustEmbedUnimplementedFileDownloaderServiceServer()
}

func RegisterFileDownloaderServiceServer(s grpc.ServiceRegistrar, srv FileDownloaderServiceServer) {
	// If the following call panics, it indicates UnimplementedFileDownloaderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileDownloaderService_ServiceDesc, srv)
}

func _FileDownloaderService_Download_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FileDownloaderServiceServer).Download(&grpc.GenericServerStream[FileDownloaderRequest, FileDownloaderResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileDownloaderService_DownloadServer = grpc.BidiStreamingServer[FileDownloaderRequest, FileDownloaderResponse]

// FileDownloaderService_ServiceDesc is the grpc.ServiceDesc for FileDownloaderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileDownloaderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analyzer.FileDownloaderService",
	HandlerType: (*FileDownloaderServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Download",
			Handler:       _FileDownloaderService_Download_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/analyzer/file_downloader_service.proto",
}
