# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/analyzer/file_scanner_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/analyzer/file_scanner_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)proto/analyzer/file_scanner_service.proto\x12\x08\x61nalyzer\"\x1b\n\x0bScanRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"0\n\x0cScanResponse\x12\x0f\n\x07started\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2Q\n\x11ScannerController\x12<\n\x0bTriggerScan\x12\x15.analyzer.ScanRequest\x1a\x16.analyzer.ScanResponseB\x06Z\x04./pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.analyzer.file_scanner_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004./pb'
  _globals['_SCANREQUEST']._serialized_start=55
  _globals['_SCANREQUEST']._serialized_end=82
  _globals['_SCANRESPONSE']._serialized_start=84
  _globals['_SCANRESPONSE']._serialized_end=132
  _globals['_SCANNERCONTROLLER']._serialized_start=134
  _globals['_SCANNERCONTROLLER']._serialized_end=215
# @@protoc_insertion_point(module_scope)
