// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: proto/account/user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// Hash Argon2id
	PasswordHash string `protobuf:"bytes,3,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	// CNIL / RGPD
	CreatedAt          int64 `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          int64 `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	TermsAccepted      bool  `protobuf:"varint,6,opt,name=terms_accepted,json=termsAccepted,proto3" json:"terms_accepted,omitempty"`
	LastPasswordChange int64 `protobuf:"varint,7,opt,name=last_password_change,json=lastPasswordChange,proto3" json:"last_password_change,omitempty"`
	// RBAC (Role Based Access Control)
	Roles         []string `protobuf:"bytes,8,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_account_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_account_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *User) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *User) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *User) GetTermsAccepted() bool {
	if x != nil {
		return x.TermsAccepted
	}
	return false
}

func (x *User) GetLastPasswordChange() int64 {
	if x != nil {
		return x.LastPasswordChange
	}
	return 0
}

func (x *User) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

var File_proto_account_user_proto protoreflect.FileDescriptor

const file_proto_account_user_proto_rawDesc = "" +
	"\n" +
	"\x18proto/account/user.proto\x12\aaccount\"\xfe\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12#\n" +
	"\rpassword_hash\x18\x03 \x01(\tR\fpasswordHash\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x03R\tupdatedAt\x12%\n" +
	"\x0eterms_accepted\x18\x06 \x01(\bR\rtermsAccepted\x120\n" +
	"\x14last_password_change\x18\a \x01(\x03R\x12lastPasswordChange\x12\x14\n" +
	"\x05roles\x18\b \x03(\tR\x05rolesB\x06Z\x04./pbb\x06proto3"

var (
	file_proto_account_user_proto_rawDescOnce sync.Once
	file_proto_account_user_proto_rawDescData []byte
)

func file_proto_account_user_proto_rawDescGZIP() []byte {
	file_proto_account_user_proto_rawDescOnce.Do(func() {
		file_proto_account_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_account_user_proto_rawDesc), len(file_proto_account_user_proto_rawDesc)))
	})
	return file_proto_account_user_proto_rawDescData
}

var file_proto_account_user_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_account_user_proto_goTypes = []any{
	(*User)(nil), // 0: account.User
}
var file_proto_account_user_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_account_user_proto_init() }
func file_proto_account_user_proto_init() {
	if File_proto_account_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_account_user_proto_rawDesc), len(file_proto_account_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_account_user_proto_goTypes,
		DependencyIndexes: file_proto_account_user_proto_depIdxs,
		MessageInfos:      file_proto_account_user_proto_msgTypes,
	}.Build()
	File_proto_account_user_proto = out.File
	file_proto_account_user_proto_goTypes = nil
	file_proto_account_user_proto_depIdxs = nil
}
